podkrepi-bg/frontend

- package.json
- yarn.lock
A suggestion/request to add [husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged) to the project.
I have added:
- husky + lint-staged to  **devDependencies**.
- husky pre-commit hook that runs `lint-staged`
> Suggestion/Request: add husky + lint-staged

- .github/pull_request_template.md
Initial Pull Request template for a review
-- https://ora.pm/project/277933/kanban/task/4482839
> feat: Create pull request template (ora ticket)

- .github/pull_request_template.md
- package.json
- tsconfig.json
_What problem are you trying to solve?_
Avoid production errors that could have been spotted by the compilator
_How did you solve the problem?_
Enable `strictNullChecks` in the TS compilator config
https://www.figma.com/blog/inside-figma-a-case-study-on-strict-null-checks/
```shell
yarn type-check
yarn build
```
> Enable strict null checks

- .gitignore
- src/components/support-form/SupportPage.tsx
- src/components/support-form/helpers/support-form.models.ts
- src/components/support-form/helpers/validation-schema.ts
- src/components/support-form/steps/AdditionalQuestions.tsx
- src/components/support-form/steps/GeneralInfo.tsx
Regarding issue #49 
Additional questions steps:
1. Changed dropdown roles to checkboxes
2. Fixed error messages appearing before submitting the text
Info step: 
1. Fixed validation on GDPR checkbox appearing before submitting
> Changed dropdown volunteer roles to checkboxes and fixed validation

- src/common/theme.ts
- src/components/auth/profile/ProfilePage.tsx
- src/components/layout/AppNavBar.tsx
- src/components/layout/Footer.tsx
- src/components/layout/LocaleMenu.tsx
- src/components/layout/LocaleSwitcher.tsx
- src/components/layout/nav/MainNavMenu.tsx
- src/components/layout/nav/MobileNav.tsx
- src/components/layout/nav/PrivateMenu.tsx
- src/components/layout/nav/PublicMenu.tsx
- Moves language selector from footer to app nav bar
- Adds language selector to profile page
- Adds better responsiveness of the app bar
- Changes default font and style of buttons as requested
Before              | After              
------------------- | ------------------
> 52 right align nav menu and move locale switcher

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- public/locales/bg/common.json
- public/locales/en/common.json
- src/components/support-form/steps/Role.tsx
- src/components/support-form/steps/Roles.tsx
Added tooltip with description for every role
To provide more information about each role
https://github.com/daritelska-platforma/frontend/issues/125 addresses only point 1 of the issue and I also have only provided dummy descriptions for each role
I am trying to help to easily be able to access the description of a role without putting weight on the UI
I used an info icon with low opacity which on hover triggers a tooltip which shows a brief description of the role
| Before              | After    |
| ![image](https://user-images.githubusercontent.com/61479393/112907470-96208400-90f6-11eb-9dfc-bd875db1ebb7.png)
| 
|
http://localhost:3040/support or http://podkrepi.bg/support
I created a new role component to encapsulate the styles and …
> Added icon with a tooltip for the description of every role

- .env.example
- .env.prod
- .github/workflows/deploy-prod.yml
- docker-compose.dev.yml
- docker-compose.prod.yml
- docker-compose.yml
- next.config.js
- One `docker-compose.yml` file to define the core services available for all environments
- The `docker-compose.dev.yml` inherits the main file and adds local source mounting points and exposes local ports
- The `docker-compose.prod.yml` inherits the main file and adds production public networking
> Update docker-compose stack with inheritance

- public/locales/bg/common.json
- public/locales/en/common.json
- src/components/support-form/SupportForm.tsx
- src/components/support-form/helpers/support-form.types.ts
- src/components/support-form/helpers/validation-schema.ts
- src/components/support-form/steps/AdditionalQuestions.tsx
Additional roles added to the volunteer section on the support form
To support more roles when volunteers want to join
https://github.com/daritelska-platforma/frontend/issues/145
Trying to make it so that when a new volunteer want to join his role will for sure be on the list for him to pick
Added additional checkboxes and translations for them on the volunteers page for every role
Should we make the roles in two columns now on larger devices or should they stay as they are ?
Also is there a set order for the roles in which they should appear on the screen ?
Before|After
---|---
Designer, PM, DevOps, Lawyer, Finances and account were missing | Added all the specified roles
Tested on both en and bg and tested the clicking of the checkboxes
http://localhost:3040/en/support (additional …
> Added additonal roles to the support form with translations

- src/components/index/sections/Jumbotron.tsx
- src/components/index/sections/SupportUsSection.tsx
- Fixed Support us section.
Desktop: 
Mobile:
- Fixed 'About Project' button bug with EN translation:
> Fix Support section and Jumbotron buttons bug

- src/components/index/sections/Jumbotron.tsx
https://user-images.githubusercontent.com/14351733/115106310-b6609780-9f6c-11eb-813d-e9dc39684a7b.mp4
> 166: Fixed homepage background cutting

- frontend/src/components/index/sections/MissionVisionGoalsSection.tsx
Fixed mission, vission, goals section spacing as discussed with @swolf86.
Desktop:
Mobile:
> [FIX][124] Fix mission, vission, goals section spacing

- frontend/src/components/privacy-policy/PrivacyPolicyPage.tsx
Added two new paragraphs in Privacy and Policy page:
> [Feature] 200 - Updated Privacy and Policy Tearms

- frontend/public/locales/bg/common.json
- frontend/public/locales/en/common.json
- frontend/src/components/privacy-policy/PrivacyPolicyPage.module.scss
- frontend/src/components/terms-of-service/TermsOfServicePage.module.scss
- Fixed GDPR text style on mobile devices.
- Removed unused translation keys.
> [FIX] 197 - Fix GDPR text style on mobile devices

- frontend/public/locales/bg/about-project.json
- frontend/public/locales/en/about-project.json
- frontend/src/components/about-project/sections/TechStack.tsx
| ![image](https://user-images.githubusercontent.com/32264020/120705363-6740d880-c4c0-11eb-9852-4cfc98f75e07.png) | ![image](https://user-images.githubusercontent.com/32264020/120705411-74f65e00-c4c0-11eb-9efe-49367081a55c.png) 
^ The first one is before, the second and third are after.
> Added translations and keys for tech stack in "about project" page

- frontend/src/common/form/validation.ts
- frontend/src/components/contact/ContactForm.tsx
Closes #224
Fixes validation of contact form and allows the users to actually submit it
> Add gdpr field to contact form

- backend/contact/database/datatypes.go
- backend/contact/database/datatypes_test.go
- backend/contact/go.mod
bugfix issue #208 
unit tests added
> [#208] fix storing JSON into DB

- frontend/src/common/util/useGTM.ts
- frontend/src/pages/_app.tsx
- frontend/src/pages/_document.tsx
> [#209] Bugfix: GTM only tracks initial page load

- frontend/src/common/routes.ts
- frontend/src/components/layout/Footer.tsx
Added Instagram social link in the footer of the page.
Before:
After:
> [Feature][250] Add Instagram social link

- .github/workflows/backend-lint.yml
- .github/workflows/backend-test.yml
- .github/workflows/frontend-lint.yml
- Added test and lint workflows for backend
- Renamed lint workflow for frontend
> Test and lint workflows for backend

- .github/workflows/deploy-nightly.yml
Scheduled nightly job run from master repo
> Change nightly run to trigger on schedule

- backend/.insomnia/Insomnia_2021-06-10.yml
- backend/.insomnia/README.md
- backend/Taskfile.yml
Threre were no install commands for the required tools
Some errors have appeared since the latest update of `protoc` tool
- https://grpc.io/docs/languages/go/quickstart/
- https://developers.google.com/protocol-buffers/docs/reference/go-generated#package
> Added protoc tools install instructions

- .github/workflows/contact.yml
- backend/contact/.devcontainer/devcontainer.json
- backend/contact/.dockerignore
- backend/contact/.gitignore
- backend/contact/Dockerfile
- backend/contact/README.md
- backend/contact/Taskfile.yml
- backend/contact/api/config/config.go
- backend/contact/go.mod
- backend/contact/main.go
- backend/contact/routes/contact/contact.go
- backend/contact/routes/healthcheck/healthcheck.go
- backend/contact/routes/support_request/support_request.go
- Added a Taskfile with lint, build, test and watch steps
- Added a short README
- Renamed module `github.com/podkrepi-bg/v2` -> `github.com/podkrepi-bg/contact`
- Updated workflow for contact module to re-use devcontainer
- Updated Dockerfile
> Update contact build

- backend/module-campaigns/nuget.config
- backend/module-campaigns/src/Podkrepibg.Campaigns.Application/Beneficiaries/Commands/CreateBeneficiary/CreateBeneficiaryCommand.cs
- backend/module-campaigns/src/Podkrepibg.Campaigns.Application/CampaignTypes/Commands/CreateCampaignType/CreateCampaignTypeCommand.cs
- backend/module-campaigns/src/Podkrepibg.Campaigns.Application/CampaignTypes/Commands/CreateCampaignType/CreateCampaignTypeValidator.cs
- backend/module-campaigns/src/Podkrepibg.Campaigns.Application/Campaigns/Commands/CreateCampaign/CreateCampaignCommand.cs
- backend/module-campaigns/src/Podkrepibg.Campaigns.Application/Campaigns/Queries/GetCampaigns/GetCampaignDetailsQuery.cs
- backend/module-campaigns/src/Podkrepibg.Campaigns.Application/Configuration/MapperConfiguration.cs
- backend/module-campaigns/src/Podkrepibg.Campaigns.Application/Podkrepibg.Campaigns.Application.csproj
- backend/module-campaigns/src/Podkrepibg.Campaigns/Podkrepibg.Campaigns.csproj
- backend/module-campaigns/src/Podkrepibg.Campaigns/Services/CampaignsService.cs
- backend/module-campaigns/tests/Podkrepibg.Campaigns.IntegrationTests/CampaignsServiceTests/BeneficiaryTests.cs
- backend/module-campaigns/tests/Podkrepibg.Campaigns.IntegrationTests/CampaignsServiceTests/CampaignTypesTests.cs
- backend/module-campaigns/tests/Podkrepibg.Campaigns.IntegrationTests/CampaignsServiceTests/CampaignsTests.cs
Uncoupled the Campaigns module from the proto files and installed the new nuget package.
Closes #261
> Install new nuget for protos. Update references.

- backend/module-campaigns/Dockerfile
Related to #309 
Since the removal of protos the campaigns module cannot be built successfully
> Remove protos from campaigns module

- .github/workflows/campaigns.yml
- .github/workflows/contact.yml
Workflow that builds contact/campaigns on each PR/push to master. Closes  #311.
> Docker build for campaigns and contact modules

- backend/module-campaigns/src/Podkrepibg.Campaigns.Application/Beneficiaries/Commands/CreateBeneficiary/CreateBeneficiaryValidator.cs
> Added notempty validation for the enum types

- frontend/src/common/theme.ts
Implemented the final changes of https://github.com/podkrepi-bg/frontend/issues/124
| ![image](https://user-images.githubusercontent.com/14351733/124146165-2d9ac780-da96-11eb-8fe0-ea3af9aa8f3a.png) | ![image](https://user-images.githubusercontent.com/14351733/124146084-152aad00-da96-11eb-88d8-16e07a9ae78a.png) |
> [FIX] 124 - Change nav styles

- frontend/src/components/index/sections/Jumbotron.tsx
Fixed scroll button on Homepage:
https://user-images.githubusercontent.com/14351733/127708214-987a0c49-f7e0-490c-b481-0ae81704d450.mp4
> [Bug] 334 - Fix scroll button on Homepage

- frontend/src/common/form/validation.ts
Disallowed special characters on name and last name input on Contact form.
> [FIX] 221 - Disallowed special characters on name input

- frontend/src/components/campaigns/CampaignCard.tsx
- frontend/src/components/campaigns/CampaignProgress.tsx
- frontend/src/components/campaigns/CampaignsList.tsx
- frontend/src/components/layout/AppNavBar.tsx
Improve campaigns listing by adding progress bar in the cart and improving donate button.
> Improve campaign carts in listing

- frontend/.env.local.example
- frontend/next.config.js
- frontend/src/styles/global.scss
- Changed config variables - KEYCLOAK_URL and GRAPHQL_URL.
- Fixed variables and functions import paths in global.scss.
> Change config variables

- frontend/package.json
- frontend/src/components/campaigns/CampaignForm.tsx
- frontend/yarn.lock
Validation needs to be improved. 
End date cannot be before start date.
> Improving date validation. End date cannot be before start date.

- package.json
- yarn.lock
We need to ensure creating of .env.local file. This simple package script take care of this. 
I am using **shx** in order to make in multi-platform.
> Improvement. Creating of .env.local will be mandatory.

- public/locales/bg/campaigns.json
- public/locales/en/campaigns.json
- src/components/campaigns/ViewCampaignPage.tsx
- src/components/campaigns/ViewCampaignProgressCard.tsx
- Papulated View camapaign page with mock data.
- Style View camapaign page.
> Populate view campaign page with mock data

- src/components/campaigns/CampaignTypeSelect.tsx
Move `error` prop to `FormControl`
> Move error prop to the nearest form control

- .babelrc
- .eslintrc.js
- jest.config.js
- package.json
- src/test/components/CopyTextButton.test.tsx
- src/test/setupTests.ts
- src/test/test-utils.tsx
- src/test/testUtils.tsx
- yarn.lock
Adding and setting up [react-testing-library](https://testing-library.com/docs/react-testing-library/intro) with [jest](https://jestjs.io/).
Added one test as an example of how we could potentially test components `CopyTextButton.test.tsx`.
Currently translation is mocked, but it is possible to set it up if we need it for testing.
"@testing-library/jest-dom"
"@testing-library/react"
"jest"
"babel-jest"
> Add testing framework

- .github/workflows/test.yml
Not sure against which node version we should test, so I'm testing against 12.x and 14.x using matrix strategy.
> Run unit tests during github PR workflows

- src/components/layout/nav/DonationMenuMobile.tsx
- src/components/layout/nav/MobileNav.tsx
Added Donation menu for mobile devices:
https://user-images.githubusercontent.com/14351733/144124361-145ba10c-ba3d-4c11-948b-8571bb179130.mp4
> Add Donation menu for mobile devices

- src/components/layout/AppNavBar.tsx
- src/components/layout/nav/DonationMenu.tsx
- src/components/layout/nav/PrivateMenu.tsx
- src/components/layout/nav/PublicMenu.tsx
- src/components/support-form/SupportForm.tsx
Show profile menu with login and register even when user is not authenticated
> Update profile menu

- package.json
- src/components/layout/Layout.tsx
- src/pages/chat.tsx
- yarn.lock
Improve transparency and integrate Discord in the webapp
https://localhost:3040/chat
https://dev.podkrepi.bg/chat
- Add link to `/chat` page in the footer or elsewhere
> Integrate discord in web

- public/locales/en/campaigns.json
- src/components/common/BankTransfer.tsx
- src/components/support-form/SupportForm.tsx
- Fixed the width of the action buttons on Support page (#497):
- Reduced the whitespace above Copy IBAN button (#509):
- Added missing EN translations for campaigns.
> Fix minor FE bugs (#497, #509), Add missing EN translations for campaigns

- src/common/hooks/coordinators.ts
- src/common/routes.ts
- src/components/coordinators/CoordinatorAddPage.tsx
- src/components/coordinators/CoordinatorBottomAppbar.tsx
- src/components/coordinators/CoordinatorDetails.tsx
- src/components/coordinators/CoordinatorModal.tsx
- src/components/coordinators/CoordinatorsForm.tsx
- src/components/coordinators/CoordinatorsGrid.tsx
- src/components/coordinators/CoordinatorsGridHelper.tsx
- src/components/coordinators/CoordinatorsPage.tsx
- src/gql/coordinators.d.ts
- src/pages/admin/coordinators/add.tsx
- src/pages/admin/coordinators/index.tsx
- src/service/apiEndpoints.ts
- src/service/coordinator.ts
Created layout for Coordinator entity
> Created layout for Coordinator entity

- src/components/layout/nav/DevelopmentMenu.tsx
- src/components/layout/nav/DonationMenu.tsx
- src/components/layout/nav/ProjectMenu.tsx
- Changed menu dropdown links color and colors on hover.
- Map the links in DonationMenu in order to be consistent with DevelopmentMenu and ProjectMenu.
| ![image](https://user-images.githubusercontent.com/14351733/155810304-8b88e82d-55fc-49a4-8de0-928a010d1fc8.png) | ![image](https://user-images.githubusercontent.com/14351733/155810278-cb9eff04-61c8-46eb-b871-f59eb77965d3.png) |
> Change menu dropdown links color

- src/components/layout/LocaleButton.tsx
- src/components/layout/LocaleMenu.tsx
- src/components/layout/LocaleSwitcher.tsx
Fixed errors on language switching in order to display the corresponding translation.
| ![before](https://user-images.githubusercontent.com/14351733/155857665-8650fc3c-804c-4c74-897a-85d70a4e6754.png)| ![after](https://user-images.githubusercontent.com/14351733/155857670-0f7ae8a5-d124-493e-9ff1-f88d441da23e.png) |
> Fix errors on language switching

- public/locales/en/countries.json
> Fix typo in countries.json

- public/locales/bg/common.json
- public/locales/en/common.json
- src/common/hooks/person.ts
- src/components/campaigns/CampaignTypeSelect.tsx
- src/components/coordinators/CoordinatorCreateSelect.tsx
- src/components/coordinators/CoordinatorsForm.tsx
- src/gql/person.d.ts
- src/service/apiEndpoints.ts
- src/service/restRequests.ts
Fetch persons and fill to select in create coordinator page
| ![154960502-8f009e54-5a2a-40fb-a2bd-836ef5010933](https://user-images.githubusercontent.com/30602242/156021854-896f12ac-891c-4aeb-beea-5efb92cfa6e4.png) | ![Screenshot at Feb 28 18-33-12](https://user-images.githubusercontent.com/30602242/156021873-ddb73977-072b-4fa0-933c-bc02e249072f.png) |
> Fetch persons and fill to select in create coordinator page

- src/components/admin/navigation/AdminLayout.tsx
Remove search from appbar from all pages in admin panel.
Close #570 
| ![Screenshot at Mar 01 17-24-25](https://user-images.githubusercontent.com/30602242/156230978-d90da06e-c264-48c2-be67-350f32d0191c.png) | ![Screenshot at Mar 01 20-54-27](https://user-images.githubusercontent.com/30602242/156231064-289dfbf0-5fcc-42e9-8c92-f2f410fe7cd8.png) |
> Remove search from appbar from all pages in admin panel.

- next.config.js
- package.json
- yarn.lock
Tried to make the build a little bit faster
on slower machines the full build is veeeery slow
the case was that some contributors avoid running full build because it is slow and commit not compilable code
full rebuild and manual testing
- `sharp` : automated image resizing
- `bundle-analyzer` : shows a heatmap with sizes of packages
> Small speedup of build and additional tooling

- public/locales/bg/cities.json
> Heading text fix

- src/components/coordinators/CoordinatorCreateSelect.tsx
- src/gql/coordinators.d.ts
Show persons that is not already coordinators in dropdown
| ![before](https://user-images.githubusercontent.com/30602242/156937781-66e56dab-53a1-425d-95c1-3763625fdcdf.png) | ![after](https://user-images.githubusercontent.com/30602242/156937785-5f393765-2c99-4631-a869-8ba3bedac7ca.png) |
> Show persons that is not already coordinators in dropdown

- src/components/campaigns/CampaignDetails.tsx
- src/components/index/sections/Jumbotron.tsx
- src/components/layout/Layout.tsx
Make home page title readable
Close #589 
|![15u281950125i81](https://user-images.githubusercontent.com/30602242/157273312-dc542503-6d58-4c29-9a8c-a64fdbb769cd.png) | ![14124](https://user-images.githubusercontent.com/30602242/157444445-dc58ceea-4ea1-4c02-afd3-32a1bdcefc25.png)|
> Make home page title readable

- src/components/campaigns/CampaignDetails.tsx
- src/components/layout/nav/AdminMenu.tsx
Fixed admin navigation items to be blue according to @TeDy-A-K's issue.
> Fixed admin navigation items to be blue

- src/components/layout/nav/PrivateMenu.tsx
For before screenshot see the linked issue.
After:
> Fixed profile menu items to be blue

- src/components/campaigns/CampaignSlider.tsx
- Added pagination:
- Hid the slider if there are no images to display.
- Hid nav arrows if there is only one image.
- Slowed down the autoplay time to 5 seconds.
> Change campaign carousel settings

- src/components/auth/profile/DonationTab.tsx
- src/components/auth/profile/PersonalInfoTab.tsx
- src/components/auth/profile/ProfilePage.tsx
- src/components/auth/profile/Tab.tsx
- src/components/layout/Layout.tsx
Apply new design to user profile page
Should close #614 
| ![before01](https://user-images.githubusercontent.com/30602242/158420045-9bbce4ec-843f-4fec-932d-fc2916de1ae2.png) | ![after01](https://user-images.githubusercontent.com/30602242/158420109-a9269938-8fc8-4b6d-b291-b9d6cb453530.png) |
| ![before02](https://user-images.githubusercontent.com/30602242/158420097-a63cb074-8fa9-4ec6-ae2d-c7dc3e72e2bf.png) | ![after02](https://user-images.githubusercontent.com/30602242/158420121-d4a315f3-84e6-41ae-a6ce-60858244e604.png) |
> Apply new design to user profile page

- src/common/hooks/withdrawals.ts
- src/components/withdrawals/CreateForm.tsx
- src/components/withdrawals/EditForm.tsx
- src/components/withdrawals/WithdrawalTypes.ts
- src/gql/withdrawals.d.ts
Create CRUD functionalities for Withdrawal entity based on https://github.com/podkrepi-bg/frontend/issues/531#issue-1148312835
> [Withdrawal] Create dashboard and CRUD functionalities

- src/components/auth/profile/CertificatesTab.tsx
- src/components/auth/profile/DonationTab.tsx
Profile page donation certificates tab
> Profile page donation certificates tab

- .env.local.example
- manifests/base/config-web.yaml
- manifests/base/deployment.yaml
- manifests/overlays/development/config-web.patch.yaml
- next.config.js
- src/common/util/campaignImageUrls.ts
- src/components/auth/profile/CertificatesTab.tsx
- src/components/campaigns/CampaignCard.tsx
- src/components/campaigns/CampaignDetails.tsx
- src/components/cities/grid/GridAppbar.tsx
- src/components/donations/modals/DetailsModal.tsx
- src/components/support-form/steps/ThankYou.tsx
- src/components/withdrawals/grid/DetailsModal.tsx
- src/gql/campaigns.d.ts
- src/pages/admin/donations/[id]/edit.tsx
- src/pages/admin/donations/index.tsx
Added loading image from api for campaign card and details components.
> Added loading image from api for campaign card and details components

- src/components/vaults/Form.tsx
- src/components/withdrawals/CreateForm.tsx
- src/components/withdrawals/EditForm.tsx
Please check issue #668 for more details.
Changes applied to: **vaults** and **withdrawals**.
you may close #668
> Reuse CurrencySelect

- src/components/campaigns/grid/CreateForm.tsx
- src/components/campaigns/grid/EditForm.tsx
- src/components/file-upload/FileList.tsx
Added functionality for adding files when editing a campaign. Should close #661
> Added functionality for adding files when editing a campaign

- src/components/admin/DeleteModal.tsx
>  Extract common reusable component for DeleteModal functionality in admin #639 

- src/components/auth/profile/PersonalInfoTab.tsx
> [Feature] Improved wording of the delete profile modal

- src/components/admin/navigation/AdminLayout.tsx
- src/components/admin/navigation/adminMenu.tsx
> Upgraded list items 

- src/components/campaigns/grid/CreateForm.tsx
- src/components/campaigns/grid/EditForm.tsx
>  [Bug] Minor - podkrepi.bg/campaigns/create overlaping validation with text on the date field #595 

- src/components/auth/profile/DonationTab.tsx
Change date format from MM/dd/yyyy to dd/MM/yyyy in user profile, donation tab.
Should close #684 
| ![Screenshot at Apr 09 09-34-07](https://user-images.githubusercontent.com/30602242/162565023-a6fa180d-9f26-45ab-b6a4-c88c1eab5297.png) | ![Screenshot at Apr 09 12-27-30](https://user-images.githubusercontent.com/30602242/162565521-2029f71f-a1ba-46ab-a2cc-93ce8115d3b7.png) |
| ![Screenshot at Apr 09 09-34-19](https://user-images.githubusercontent.com/30602242/162565050-6091f9e8-7a94-45f9-a66b-c9e81071390e.png) | ![Screenshot at Apr 09 12-27-42](https://user-images.githubusercontent.com/30602242/162565525-ed0cdae9-d6fc-40d5-a0b0-3d935ea2b075.png) |
> Change date format from MM/dd/yyyy to dd/MM/yyyy in user profile

- src/components/auth/login/LoginPage.tsx
Redirect user to same page before login page
Should close #683 
https://user-images.githubusercontent.com/30602242/162568877-f91a1fd7-9b1d-4baf-9cb1-f04e49983301.mp4
> Redirect user to same page before login page

- src/components/auth/profile/PersonalInfoTab.tsx
Redirect user to keycloak to change password from user profile
Should close issue #698
> Redirect user to keycloak to change password

- README.md
We need to have a description of how to start the StripeCLI in order to be able to test functionality connected to the donations.
> Add description of how to start the stripe cli

- src/components/layout/nav/DonationMenuMobile.tsx
> user to be redirected to a new page with info about FAQ on mobile device

- src/components/common/form/FormSelectField.tsx
We didn't have a Select component to wrap around the `Formik` functionality which I think can be useful in forms around the app.
> Add form select field common component

- src/common/util/useCurrentPerson.ts
- src/components/auth/profile/DonationTab.tsx
- src/components/auth/register/RegisterPage.tsx
- src/service/apiEndpoints.ts
> Added request for creating user after registration

- src/components/common/CopyTextButton.tsx
- Changed the colors (default and copied) of Copy IBAN button:
| ![1](https://user-images.githubusercontent.com/14351733/166290785-52aa46e4-b893-4a2e-8f99-fc172c5507d6.png) | ![2](https://user-images.githubusercontent.com/14351733/166290396-7ec9e00c-79b6-415e-9c73-de3caf6289e4.png) |
> Change colors of Copy IBAN button

- src/common/hooks/campaigns.ts
- src/components/campaigns/grid/CampaignGrid.tsx
- src/components/campaigns/grid/modals/DetailsModal.tsx
- src/gql/campaigns.ts
- src/service/apiEndpoints.ts
At the moment campaigns are filtering by state (only active and comleted are shown). As admin I have to see all of the campaings and new route is used that returns all campaings with needed data.
> Updated getting of data for campaign grid

- src/components/auth/profile/DonationTable.tsx
- src/gql/donations.d.ts
- src/pages/api/pdf/certificate/[donationId].tsx
- src/service/apiEndpoints.ts
In the list with user donations there is button that has to generate certificate for each donation.
> Added caling of pdf generation, updated data fetch in the handler

- src/components/auth/profile/CertificatesTab.tsx
- src/components/auth/profile/DonationAgreementTab.tsx
- src/components/auth/profile/DonationTab.tsx
- src/components/auth/profile/PersonalInfoTab.tsx
- src/components/auth/profile/ProfilePage.tsx
- src/components/auth/profile/ProfileTab.tsx
| ![Screenshot 2022-05-14 at 17 37 11](https://user-images.githubusercontent.com/105493182/168430596-2131fa87-c7bb-4f43-a82b-a73e4ad8779a.png) |![image](https://user-images.githubusercontent.com/67734870/171606636-5ed004db-d0fa-4dd6-bc17-141d215a11f0.png)|
> personal info design closer to the figma requirements

- src/components/campaigns/CampaignFilter.tsx
- src/components/campaigns/CampaignsList.tsx
| ![image](https://user-images.githubusercontent.com/67734870/171629883-b674ed0a-50f3-4d5b-9547-d085edd7d081.png) |![image](https://user-images.githubusercontent.com/67734870/171630285-7142eba7-e587-46a0-8461-03710d573e31.png) |
| Chrome-empty              | Mozilla-empty              |
|![image](https://user-images.githubusercontent.com/67734870/171631262-e2c31682-d30f-4736-bc1c-53ea820b563e.png)|![image](https://user-images.githubusercontent.com/67734870/171630994-00179c31-865e-4d63-83d9-c1ffdace4f04.png)|
- …
> 805 bug big loading circle on campaign list page

- src/components/irregularity/admin/grid/IrregularityFile.tsx
- src/service/apiEndpoints.ts
- src/service/irregularity.ts
> authorized file download request

- src/common/util/money.ts
- src/components/campaigns/grid/CampaignGrid.tsx
- src/components/campaigns/grid/CreateForm.tsx
- src/components/campaigns/grid/EditForm.tsx
- src/components/campaigns/grid/modals/DetailsModal.tsx
Fixes https://github.com/podkrepi-bg/frontend/issues/836
CampaignCreate and CreateEdit forms needed to have conversion of the money coming from the API, so added to/fromMoney functions to make the correct conversions.
> Fixed targetAmount decimal calculation

- src/components/campaigns/CampaignDetails.tsx
- src/components/campaigns/CampaignInfo.tsx
- src/components/campaigns/InlineDonation.tsx
- src/components/campaigns/ViewCampaignPage.tsx
> Apply responsive styles on Campaign Details page

- src/components/campaigns/CampaignCard.tsx
> Fixes image display in campaign card

- package.json
- public/locales/bg/campaigns.json
- src/common/hooks/campaigns.ts
- src/components/campaigns/CampaignDetails.tsx
- src/components/campaigns/CampaignForm.tsx
- src/components/campaigns/CampaignInfo.tsx
- src/components/campaigns/DonorsAndDonations.tsx
- src/components/campaigns/grid/CoordinatorSelect.tsx
- src/components/campaigns/grid/CreateForm.tsx
- src/components/campaigns/grid/EditForm.tsx
- src/components/campaigns/grid/modals/DetailsModal.tsx
- src/components/donations/grid/Grid.tsx
- src/gql/campaigns.ts
- src/service/apiEndpoints.ts
- increased campaign description to 20000 symbols
- version changed to 0.9.9
- fixed typo in cordinator->coordinator
- fixed: now possible to create/edit campaign without setting end-date
- reduced the huge campaign title
> campaign creation improvements

- src/components/campaigns/InlineDonation.tsx
- src/components/campaigns/helpers/socialMedia.ts
| NONE | ![image](https://user-images.githubusercontent.com/67734870/177329661-dacc2914-f841-4caa-801d-bfa515323192.png) |
> 844 feature button for sharing a campaign needs to be enabled

- public/locales/en/common.json
- src/components/campaigns/InlineDonation.tsx
| ![image](https://user-images.githubusercontent.com/67734870/177963232-8048ff66-b9d3-47a9-a21f-bb146a888d0b.png) | ![image](https://user-images.githubusercontent.com/67734870/177964038-ba0cf85f-fc75-4760-9375-b40e10427f51.png)|
> Removed list price and redirect to one time donation

- src/components/campaigns/CampaignDetails.tsx
|---------------------|-------------------|
| ![image](https://user-images.githubusercontent.com/67734870/177944281-40be8013-15d8-4c5b-82a9-37a65dd9395c.png) |![image](https://user-images.githubusercontent.com/67734870/177946176-b985783a-de4e-4f7c-a30a-cd325da0d154.png) |
>  Campaign description style

- public/locales/bg/campaigns.json
- public/locales/en/campaigns.json
- src/components/campaigns/CampaignInfo.tsx
| ![image](https://user-images.githubusercontent.com/67734870/177958304-56cc55a2-7842-454b-b505-119e7a6dbfa4.png)|![image](https://user-images.githubusercontent.com/67734870/177958043-fdabc641-0b69-49bb-bb6d-5fb9ccd3cce7.png)|
> translated campaign status

- src/components/campaigns/CampaignDetails.tsx
- src/components/campaigns/InlineDonation.tsx
- src/components/campaigns/ViewCampaignPage.tsx
- src/components/layout/nav/DonationMenu.tsx
- src/components/layout/nav/DonationMenuMobile.tsx
> Created mobile view of InlineDonation component

- src/components/donations/grid/Grid.tsx
- src/gql/donations.d.ts
> Error on displaying donations in grid

- src/components/campaigns/CampaignInfo.tsx
- src/components/campaigns/CampaignTypeSelect.tsx
- src/components/campaigns/grid/CampaignGrid.tsx
- src/components/campaigns/grid/modals/DetailsModal.tsx
This issue removes the translation of campaign types.
> removed: campaign type translation

- src/components/one-time-donation/steps/SecondStep.tsx
|![image](https://user-images.githubusercontent.com/7055304/179153611-25f8b7e4-c374-4758-a1e1-ee3db0310505.png)|![image](https://user-images.githubusercontent.com/67734870/179191238-a9f10073-6280-4205-a5ed-d05c2ee411d9.png) |
> Tab orientation vertical when mobile device

- manifests/README.md
- manifests/overlays/production/keycloak-config-web.patch.yaml
- manifests/overlays/production/kustomization.yaml
Bumped versions for production deployment
Fixed keycloak to point to keycloak-dev which is the upgraded server for production
> bumped versions and fixed prod to point to keycloak-dev

- src/common/util/money.ts
- src/components/campaigns/CampaignCard.tsx
- src/components/campaigns/CampaignsList.tsx
- src/components/index/sections/CampaignsSection.tsx
- src/components/index/sections/Jumbotron.tsx
[https://drive.google.com/file/d/11BPG_qZkbuTws-7KXIsyRbNXtHkBaO-8/view?usp=sharing](https://drive.google.com/file/d/11BPG_qZkbuTws-7KXIsyRbNXtHkBaO-8/view?usp=sharing)
> Refactoring campaign card and list

- src/components/index/helpers/teamMembers/MemberCard.tsx
- src/components/index/sections/HowWeWorkSection.tsx
- src/components/index/sections/Jumbotron.tsx
- src/components/index/sections/ReadyToStartCampaignSection.tsx
- src/components/index/sections/WantToHelpPodkrepiBg.tsx
[homepage-responsive.webm](https://user-images.githubusercontent.com/14351733/180091742-b36e36cb-6af2-4089-8b85-f2b3338cc7ce.webm)
> Fix responsive styles on Homepage

- public/locales/bg/index.json
- public/locales/en/index.json
> Replaced causes with campaigns on main page

- src/components/auth/profile/DonationTable.tsx
- src/gql/donations.d.ts
> Personal profile donations link to campaigns

- manifests/overlays/production/kustomization.yaml
- package.json
- v0.9.11
- updated: prod deployment to v0.9.11
> release v0.9.11

- src/common/hooks/campaigns.ts
- src/components/campaigns/InlineDonation.tsx
- src/gql/campaigns.ts
- To fix the following error when opening campaigns:
> Fixed bug campaign donation history

- src/common/hooks/donationWish.ts
- src/components/campaigns/CampaignDetails.tsx
- src/components/campaigns/CampaignMessages.tsx
- src/components/one-time-donation/Steps.tsx
- src/gql/donationWish.d.ts
- src/gql/donations.d.ts
- src/service/apiEndpoints.ts
- src/service/donationWish.ts
> [Feature] Donation wish

- src/components/campaigns/CampaignCard.tsx
- yarn.lock
> Fix navigation and title for campaign cards

- src/components/auth/profile/ProfilePage.tsx
- src/components/auth/profile/tabs.tsx
| ![image](https://user-images.githubusercontent.com/67734870/181740457-ff8aca52-9e18-4ab5-b310-4f67b518b602.png) | ![image](https://user-images.githubusercontent.com/67734870/181740803-4e2b317a-116b-4af2-8f83-277d82078ee7.png) |
> Hide contract section

- src/common/util/date.ts
- src/components/admin/navigation/adminMenu.tsx
- src/components/donations/grid/Grid.tsx
- src/components/one-time-donation/LoginForm.tsx
- src/components/one-time-donation/RegisterDialog.tsx
- src/components/support-form/steps/Roles.tsx
- fixed: minutes of formated date to mm instead of ii
- moved donation card as second in Admin UI
- added: billingName and Mail to be visible and reordered columns
- cleanup lint errors
> Adding billingName and Email to AdminDonations Grid

- public/locales/bg/profile.json
- public/locales/en/profile.json
- src/components/auth/profile/CertificatesTab.tsx
- src/components/auth/profile/DonationTab.tsx
- src/components/auth/profile/DonationTable.tsx
[Screencast from 29.07.2022 14:34:51.webm](https://user-images.githubusercontent.com/67734870/181751347-fd7a12c7-bad7-406e-9210-30590f0ba87b.webm)
[Screencast from 29.07.2022 14:36:12.webm](https://user-images.githubusercontent.com/67734870/181751423-62c019e3-67ba-49cd-aa79-41a67de97bbf.webm)
[Screencast from 29.07.2022 14:36:52.webm](https://user-images.githubusercontent.com/67734870/181751543-62e1f207-24c8-4191-8d7f-daf522d6fb2f.webm)
> Certificate table functionality

- src/components/campaigns/CampaignInfoCoordinator.tsx
- src/components/campaigns/CampaignInfoOrganizer.tsx
Fixed organizer and coordinator wrappers so that longer names do not fall bellow the logo:
> Fix organizer and coordinator wrappers

- public/locales/bg/auth.json
- public/locales/en/auth.json
- src/components/auth/register/RegisterForm.tsx
| ![image](https://user-images.githubusercontent.com/67734870/182814504-db034575-ca66-45a7-8585-e21adcb30899.png)|![image](https://user-images.githubusercontent.com/67734870/182819972-f28aef56-f7d4-44ad-9ed3-0b493dc35c1f.png)|
[Screencast from  4.08.2022 12:46:07.webm](https://user-images.githubusercontent.com/67734870/182817998-ecb802ea-4fc9-4a01-9042-771450235d92.webm)
> Name field validations and confirm password field

- src/components/campaigns/ViewCampaignPage.tsx
https://user-images.githubusercontent.com/14351733/182938300-d7f7004c-9c2f-4155-848e-848556ad1b8b.mp4
> Add sticky for mobile Donation menu

- src/components/campaigns/CampaignCard.tsx
- src/components/campaigns/CampaignsList.tsx
- src/components/index/sections/Jumbotron.tsx
- src/components/layout/ImproveThisPageTag.tsx
- Reduced title's and subtitle's font size and width:
| ![image](https://user-images.githubusercontent.com/14351733/182918110-5ed0fcf0-43c0-40a0-8da0-213ce6cf380c.png) | ![image](https://user-images.githubusercontent.com/14351733/182917910-b76b0bcb-1e68-4bcf-966d-97b88e2742a3.png) |
- Updated campaign's title:
| ![title1](https://user-images.githubusercontent.com/14351733/182919478-b7f04832-1cda-4bb8-a9dd-0ce191bd14df.png) | ![title2](https://user-images.githubusercontent.com/14351733/182919544-33cad8eb-e919-41f5-b262-5674701ca873.png) |
- Fixed responsive issue on iPad resolution - campaign card buttons …
> Fix Homepage and Campaigns page UI issues

- .github/workflows/release.yml
- Dockerfile
Set the correct version (same as the tag) when building the frontend container
> Set proper version in package.json when building frontend container

- src/components/campaigns/CampaignCard.tsx
- Added campaign subtext to campaign card:
> Add campaign subtext to campaign card

- public/locales/bg/profile.json
- public/locales/en/profile.json
- src/components/auth/profile/CertificatesTab.tsx
| ![image](https://user-images.githubusercontent.com/16187050/184503269-912a4e87-c722-4418-9d92-8d7af3ffb608.png) |![image](https://user-images.githubusercontent.com/67734870/184533009-f2cb6920-1268-4ac8-961b-5331c3b7629e.png) |
> Certificates page translation

- public/locales/bg/common.json
- public/locales/en/common.json
- src/components/index/sections/Jumbotron.tsx
- src/components/layout/AppNavBar.tsx
- src/components/layout/LocaleButton.tsx
- src/components/layout/nav/DonationMenu.tsx
- src/components/layout/nav/GenericMenu.tsx
- src/components/layout/nav/MainNavMenu.tsx
- src/components/layout/nav/PrivateMenu.tsx
- src/components/layout/nav/ProjectMenu.tsx
- src/components/layout/nav/PublicMenu.tsx
[screencast-localhost_3040-2022.08.17-20_03_16.webm](https://user-images.githubusercontent.com/14351733/185200029-6f698fc4-ae6d-4239-b231-78c202c33049.webm)
> Update global navigation

- src/components/about/helpers/managementBoardData.tsx
- src/components/about/sections/ManagementBoardSection.tsx
- src/components/about/sections/SupervisoryBoardSection.tsx
This PR will collect updates for About Us page
- made linkedin link optional as some people don't have linkedin profile
> About Us page updates

- src/components/campaigns/CampaignDetails.tsx
Fixed the issues seen in the screenshot above: transformed beneficiary name to start with capital letter and added spacings.
> Fix Campaign details UI issues

- src/common/form/validation.ts
Added ' " + = - to the allowed special symbols in the password regex:
> Update password regex

- src/components/auth/register/RegisterForm.tsx
> Add Terms and Conditions and GDPR to Registration form

- src/components/index/sections/CampaignsSection.tsx
Increased visible campaigns on Homepage to 4:
> Update Campaigns section on Homepage

- src/components/campaigns/CampaignDetails.tsx
> Fix campaign title

- README.md
- src/components/layout/Layout.tsx
To enable additional Google Analytics optimizations
- added: google optimize script in HEAD
- fixed: linting erros
> Added Google Optimize Header

- next.config.js
- src/components/one-time-donation/steps/FirstStep.tsx
An unexperienced developer(myself) is trying to figure out how to load config variables
> fixing config paypal_client_id

- public/locales/bg/campaigns.json
- src/common/util/shuffle.ts
- src/components/auth/profile/MyCampaignsTable.tsx
- src/components/auth/profile/MyDonatedToCampaignsTable.tsx
- src/components/campaigns/CampaignFilter.tsx
- src/components/campaigns/grid/CampaignGrid.tsx
- src/components/index/sections/CampaignsSection.tsx
Removed description field from campaign grids because it was not readable richtext. It is removed on backend too in this PR:https://github.com/podkrepi-bg/api/pull/347
> Removed desription field from campaign grids

- src/components/campaigns/CampaignsList.tsx
- src/components/index/sections/CampaignsSection/CampaignsSection.tsx
Increase visible campaigns number on Homepage and Campaigns listing page from 8 to 12.
> Increase visible campaigns number

- src/components/campaigns/ViewCampaignPage.tsx
| ![image](https://user-images.githubusercontent.com/14351733/202101244-88376b83-21b7-4cee-95a2-a093b872b158.png) | ![Screenshot 2022-11-16 081815](https://user-images.githubusercontent.com/14351733/202100234-8c2e83d5-24a0-47d6-b66a-8874f6752c2b.png) |
> Fix overlapping bug in Campaign Details page for Firefox browser

- src/components/common/BankTransfer.tsx
Added IBAN trimmed value on click copy button
Link to issue: [https://github.com/podkrepi-bg/frontend/issues/1109](url)
> 1109 - trimmed IBAN value on copy click

- .github/workflows/playwright.yml
- playwright.config.ts
Starts stripe webhook before playwright tests
> CI stripe webhook

- src/components/layout/Footer/helpers/FooterData.tsx
Updated the Blog link in Footer not to be opened as external link in a new tab.
> Update Blog link in Footer

- src/components/campaigns/CampaignDetails.tsx
- src/components/campaigns/grid/CampaignGrid.tsx
- src/components/campaigns/grid/modals/DetailsModal.tsx
- src/components/one-time-donation/OneTimeDonationPage.tsx
Added a nullsafe check to the person. property since it is not existent! 
Need to update the type!!
> Add nullsafe check to the beneficiary.person

- src/components/campaigns/DonorsAndDonations.tsx
I've chosen to use formatDistanceStrict, because formatDistance will add "**about** 8 hours, **about** 8 days ago" etc
Closes #{1208}
Issue [https://github.com/podkrepi-bg/frontend/issues/1208](url)
Before: 
After:
> 1208 Changed date-fns function to not break the line

- README.md
- e2e/helpers.ts
- e2e/local/campaigns.spec.ts
- e2e/local/donation.spec.ts
- playwright.config.ts
- src/components/index/sections/Jumbotron/Jumbotron.tsx
- src/components/one-time-donation/steps/FirstStep.tsx
Does not have an issue, but might be a good idea to create some general epic for the testing?
Added more tests to the donation flow and the campaigns page.
There isn't much to see, except one bad workaround of clipboard testing.
Would love to get feedback from the QA team and if they have suggestions for improvements it would be nice.
Can't add @ovcharski (https://github.com/ovcharski) as a reviewer so I hope he sees that
> [Testing] E2e tests donation by bank and campaigns

- public/locales/bg/profile.json
- src/components/layout/nav/AdminMenu.tsx
- src/components/layout/nav/PrivateMenu.tsx
- src/gql/next-auth.d.ts
- src/pages/api/auth/[...nextauth].ts
- Combines and improves the type system for NextAuth user session and JWT
- Changes the `Login информация` label to `Данни за вход:`
- Fixes potential runtime errors based on the new types
1. Login
2. Go to profile page
3. Page should be rendered OK
- http://localhost:3040/profile/personal-information
> Improve typing of user session

- src/components/layout/nav/MainNavMenu.tsx
Closes #1247
Use a different button component that can handle locales when routing. Now, clicking on the donate button, correctly preserves the already selected local (BG or EN) in the route. 
There were slight changes to the styling of the button, remedied most important ones by using some inline styles. 
Before|After
---|---
- When BG lang is selected, clicking on the Donate button routes to correct page in BG lang.
- When EN lang is selected, clicking on the Donate button routes to correct page in EN lang.
http://localhost:3040/campaigns
http://localhost:3040/en/campaigns
> 1247-Fix main menu donate button routing.

- src/components/campaigns/grid/CampaignGrid.tsx
increased paging in admin campaign grid to 10
> increased campaigns paging to 10

- src/components/layout/nav/PrivateMenu.tsx
Hotfix for Sentry issue #3892483132
> avatar-letters-hotfix - add a fallback to `given_name` and `family_name`

- src/components/campaigns/CampaignsPage.tsx
> Fix the header on Campaigns listing page

- src/common/util/money.ts
Updated money representation in order to increase the transparency.
Before|After
---|---
> Update money representation

- package.json
- src/decs.d.ts
- yarn.lock
Updated @react-pdf/renderer to get typing
removed declare module in decs.d.ts
Closes #1312
> Fix: Update React Pdf Renderer

- src/common/util/campaignImageUrls.ts
> Display avatars on campaign details page on local environment

- src/components/campaigns/DonorsAndDonations.tsx
Increase number of donators in Donation component on Campaign details page. This also fixes the donations' count issue.
Before|After
---|---
> Increase number of donations in Donation component

- src/components/common/LinkButton.tsx
Closes #1327 #1328 
Closing the above mentioned issues, thus improving the accessibility.
Navigate with the TAB key to the campaign card buttons.
Check if there is a invisible tabbable element.
Check if disabled button can receive focus-visible property.
> common/LinkButton.tsx: Manage tabIndex property correctly

- src/components/layout/NotificationSnackBar/NotificationSnackBar.tsx
- src/components/layout/NotificationSnackBar/props/global.ts
use transitionDuration field for delay open
Closes #{issue number}
Before|After
---|---
> Update the notification display time

- src/components/campaigns/CampaignDetails.tsx
- src/components/campaigns/CampaignInfoGraphics.tsx
- src/components/campaigns/DonationWishes.tsx
- src/pages/_document.tsx
- Fixed font discrepancy on Campaign details page.
- Updated Donation Wishes styles according to the new design.
Before|After
---|---
> Update Donation Messages styles

- src/components/client/campaigns/DonorsAndDonations.tsx
Closes #{1369}
Issue [https://github.com/podkrepi-bg/frontend/issues/1369](url)
> Fixed broken styles of donation information on Safari

- src/components/client/campaigns/CampaignDetails.tsx
- src/components/client/campaigns/InlineDonation.tsx
Added the following UI fixes for tablet and mobile devices:
- Spacing between the Donation component and the campaign title.
- Box shadow effect to the see more button on Donation component.
- Space above the donated and target sums for tablet devices.
Before|After
---|---
> Add minor responsive UI fixes on Campaign details page

- src/common/routes.ts
- src/components/admin/partners/PartnersContent.tsx
- src/components/admin/partners/helpers/partnersData.ts
issue #1367 logos image now redirects to partner's pages.
todo : some websites are hard coded to google just because i don't have the correct urls
> logo images now redirects to partners pages

- next.config.js
Added recommended security headers to prevent IFRAME clickjacking and XSS as per https://nextjs.org/docs/advanced-features/security-headers
> added security headers

- src/components/client/about-project/FinanceReportPage.tsx
Closes #1379 
To fix problem with pdf finance reports on English.
In future if finance reports in English are added ,the LinkButton and routing will need to be refactored. 
Before|After
---|---
> Temporary bug fix for finance reports in english

- src/components/client/index/IndexPage.tsx
- Move Platform Statistics section below Completed campaigns as per design.
Before|After
---|---
> Update Platform Statistics section UI

- src/common/form/validation.ts
Added ), ( and : symbols as valid: 
Before|After
---|---
> Update password validation regex on Registration form

- src/components/client/one-time-donation/OneTimeDonationPage.tsx
- src/components/client/one-time-donation/OneTimeDonationPage/OneTimeDonation.styles.tsx
- src/components/client/one-time-donation/OneTimeDonationPage/OneTimeDonationPage.tsx
- src/pages/campaigns/donation/[slug].tsx
> Remove campaign banner on donation page

- src/components/client/one-time-donation/AnonymousForm.tsx
Preventive measure against users' shenannigans
Complementary to [#503](https://github.com/podkrepi-bg/api/pull/503)
> AnonymousForm.tsx: Disable field if user is logged in

- src/components/client/layout/Footer/helpers/FooterData.tsx
- src/pages/campaigns/create.tsx
Temporary render NotFoundPage, until support for suggesting new campaign is implemented
Closes: Reported in Discord
> campaigns: Remove suggest campaign link

- src/components/client/auth/changePassword/ChangePasswordForm.tsx
Matches the behavior from registration and profile password change form
Closes: Reported in discord
> ChangePasswordForm.tsx: Fix password validation

- src/pages/_app.tsx
Reverts PR podkrepi-bg/frontend#1457 as now there is improvement to not open too many connections in PR https://github.com/podkrepi-bg/frontend/pull/1460
> Revert "temporary switched off donation notification popups"

- src/components/client/campaigns/CampaignPublicExpensesGrid.tsx
Closes: Reported in discord
Its a bug..
> CampaignPublicExpensesGrid.tsx: Fix filtering on date

- public/locales/en/campaigns.json
- src/components/admin/campaigns/grid/CampaignGrid.tsx
#1064 
due to the migration to the new data grid, some of these features work as expected, just minor improvements to meet the requirements
> improvements to campaign grid

- public/locales/bg/index.json
- public/locales/en/index.json
- src/common/routes.ts
- src/components/admin/partners/helpers/partnersData.ts
- src/components/client/index/IndexPage.tsx
- src/components/client/index/sections/MediaSection/MediaSection.styled.tsx
- src/components/client/index/sections/PartnersSection/PartnersSection.styled.tsx
- src/components/client/index/sections/PartnersSection/PartnersSection.tsx
- Implemented Partners section:
- Updated Media section - default background and hover effect:
> Implement Partners section, update Media section

- src/components/admin/AdminPage.tsx
Improving the design of the admin page.
Before:
After:
> change the design of the admin page

- src/components/common/person/grid/DetailsModal.tsx
Remove characters between first and last name in user details modal window
Before:
After:
> remove characters between firstName and lastName

- src/components/client/support-us-form/SupportUsForm.tsx
Closes Reported in discord
its a bug
Before|After
---|---
> SupportUsForm.tsx: Fix missing donation details

- src/common/hooks/campaigns.ts
- src/components/client/auth/profile/MyDonatedToCampaignsTable.tsx
- src/service/apiEndpoints.ts
https://github.com/podkrepi-bg/frontend/issues/1477
discussed with @igoychev i think this fixes the issue
> my campaigns is now visible

- public/locales/bg/expenses.json
- src/components/admin/expenses/grid/DetailsModal.tsx
- src/components/admin/expenses/grid/Grid.tsx
Improvements:
- column "Deleted" - removed
- checkboxes - removed
- action buttons - moved to the left side
> expenses-improvements

- src/components/admin/cities/EditForm.tsx
- src/components/admin/cities/grid/CityGrid.tsx
> cities - translations added

- src/components/admin/coordinators/grid/CoordinatorsGrid.tsx
> coordinators-fix

- src/components/admin/InfoRequestBottomAppBar.tsx
- src/components/admin/bankaccounts/grid/GridAppbar.tsx
- src/components/admin/coordinators/grid/GridAppbar.tsx
remove buttons that are not used
> remove buttons that are not used

- package.json
- src/common/theme.ts
- yarn.lock
> Remove deprecated font

- src/common/hooks/campaigns.ts
- src/pages/campaigns/donation/[slug].tsx
We've been sending the object, rather than the url.
Closes #1496
> pages/campaigns: Fix wrong prefetch url on donation page

- public/locales/bg/campaigns.json
- public/locales/en/campaigns.json
- src/components/client/campaigns/InlineDonation.tsx
> Add currency on campaign details for BG

- src/components/client/index/sections/PlatformStatisticsSection/Statistics/Statistics.styled.tsx
- src/components/client/index/sections/PlatformStatisticsSection/Statistics/Statistics.tsx
> Update donated money in Statistics on Homepage

- src/components/client/support-us-form/SupportUs.styled.tsx
- src/components/client/support-us-form/SupportUsForm.tsx
- src/components/client/support-us-form/SupportUsPage.tsx
Before|After
---|---
Before|After
---|---
> Update Support us form for mobile devices

- src/components/client/campaigns/InlineDonation.tsx
- src/components/client/layout/Footer/LogoSocialIcons.tsx
Temporarily hide subscribe buttons, till everything around the system is ready.
> Hide subscribe buttons for notifications[TEMPORARY]

- src/components/client/campaigns/CampaignInfo/CampaignInfoStatus.tsx
Related to https://github.com/podkrepi-bg/frontend/issues/1430
Before|After
---|---
> Update Chips' styling on campaign details

- src/common/hooks/bank-transactions.ts
- src/components/admin/bank-transactions/grid/Grid.tsx
- src/service/apiEndpoints.ts
Closes #1588 
* Bank transactions are now sorted in descending order (by transaction date).
> Sort bank transactions by descening transactionDate

- src/components/client/campaign-news/CampaignNewsList.tsx
- src/components/client/campaign-news/CampaignNewsPage.tsx
> Update Campaign News UI

- src/components/client/campaign-news/CampaignNewsList.tsx
Remove the max-width of Typography as it is redundant now..
Closes #1604 
Fixes layout bug
> CampaignNewsList.tsx: Set max-width of 1200px to container

- src/components/client/one-time-donation/steps/FirstStep.tsx
- src/components/client/support-us-form/SupportUsForm.tsx
> Update alignment of Bank details on Donation (mobile)

- package.json
- yarn.lock
> upgrade_sentry_to_7.80

- src/components/admin/bank-transactions/grid/RerunTransactionsSyncDialog.tsx
- src/components/admin/donations/grid/GridAppbar.tsx
> disabled button for manual import, added guard in rerun button

- next.config.js
- public/robots.txt
- src/pages/api/robots.ts
* Disallow crawling in the robots.txt for non-production environments
Closes #1246
> make the robots.txt file dynamic

- src/components/client/campaigns/CampaignCard/CampaignCard.tsx
- src/components/client/campaigns/CampaignDetails.tsx
- src/components/client/campaigns/InlineDonation.tsx
- src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.tsx
guaranteedAmount is missing in the campaign/list response.
> client/Campaigns: Fix NaN due to guaranteedAmount missing

- .github/workflows/release.yml
- .github/workflows/tests.yml
The production deployment seems to be failing by some reason.
We want to disable those tests temporarily.
> Disable the k8s tests from both release and test

- public/locales/bg/campaigns.json
- public/locales/en/campaigns.json
- src/components/client/campaigns/CampaignInfo/CampaignInfoStatus.tsx
New campaign types are added dynamically through the admin panel, thus some translation could be missing in the file. Use name of campaignType until we figure out a way to translate them dynamically.
> CampaignInfo.tsx: Use category of  type to translate campaign type

- src/pages/contact.tsx
> Fix translations on Contact page

- public/locales/bg/about-project.json
- public/locales/en/about-project.json
The change is requested by Petya Dimitrova.
> Update Finance reports title

- src/components/client/layout/nav/AuthLinks/AuthLinks.styled.tsx
- src/components/client/layout/nav/DonationMenuMobile.tsx
- src/components/client/layout/nav/MobileNav/MobileNav.styled.tsx
- src/components/client/layout/nav/ProjectMenuMobile.tsx
> font size/weight for mobile devices  changed

- src/components/admin/payments/grid/Grid.tsx
Fixes filtering by payment id, in admin panel
> admin/payments: Fix filtering by payment id

- src/components/client/layout/Footer/LogoSocialIcons.tsx
- src/components/client/notifications/SubscriptionPage.tsx
- src/components/common/LinkButton.tsx
Makes subscription page responsive
> ui: Make subscription page responsive

- src/components/common/form/CheckboxField.tsx
After click on checkbox moving page one pixel on register page #1824
Closes #{1824}
margin-top is set to 0
> After click on checkbox moving page one pixel on register page #1824

- src/pages/api/auth/[...nextauth].ts
- src/service/auth.ts
Front-end adjustments, needed by [backend#640](https://github.com/podkrepi-bg/api/pull/640)
Closes #1762
> [2/2]fix: Link existing users to identity providers on user exists error

- src/components/client/campaign-application/CampaignApplicationForm.tsx
- src/components/client/campaign-application/CampaignApplicationRemark.tsx
Add a remark in the campaign application stepper skeleton connected to [Epic #1842](https://github.com/podkrepi-bg/frontend/issues/1842)
2. Visit `http://localhost:3040/campaigns/application`
> feat: add remark in the campaign application stepper (Epic #1842)

- src/components/common/errors/NotFoundPage/NotFoundPage.styled.tsx
- src/components/common/errors/NotFoundPage/NotFoundPage.tsx
Changed Back button on Not Found page to redirect to the previous page. 
The original styles are saved.
> Change Back button on Not Found page to redirect to the previous page

- public/locales/bg/common.json
- public/locales/en/common.json
- src/components/admin/affiliates/AffiliatesPage.tsx
- src/components/client/campaign-news/CampaignNewsList.tsx
- src/components/client/campaigns/CampaignFilter.tsx
- Update typos that affect the styles.
- Update Open data titles to achieve consistency in the navigation and Open data page.
> Update typos and texts

- public/scroll-to-top-icon.svg
- src/components/client/layout/ScrollToTop.tsx
> Update Scroll to top button

- public/locales/bg/campaigns.json
- public/locales/en/campaigns.json
- src/components/client/campaigns/CampaignDetails.tsx
- Updated 'Report an irregularity' button on Campaign page.
- Removed feedback button.
Before|After
---|---
- Rearranged file imports.
> Update 'Report an irregularity' button on Campaign page

- src/components/client/notifications/CampaignSubscribeModal.tsx
> Update Subscription modal translations on Campaign details page

- .devcontainer/devcontainer.json
just a whitespace fix that otherwise pop up after every commit
> fix: whitespace

- src/components/admin/partners/helpers/guarantsData.ts
Closes [issue-1927](https://github.com/podkrepi-bg/frontend/issues/1927)
> updated person ivaylo marinov data

- src/components/client/auth/profile/DisableAccountModal.tsx
Closes #[issue-1908](https://github.com/podkrepi-bg/frontend/issues/1908)
Before|After
---|---
> fixed links for unsubscribe and contacts

- src/components/client/campaigns/CampaignPublicExpensesGrid.tsx
Updates the cerfiticate date format from MM/DD/2024 to DD MM YYYY
Closes #{1971}
Changed the date format
> fix certificate date format

- src/components/admin/recurring-donation/grid/Grid.tsx
- src/components/client/auth/profile/MyRecurringCampaignsTable.tsx
- src/service/apiEndpoints.ts
- src/service/donation.ts
Closes #{issue number}
Before|After
---|---
> fix: User unable to cancel their donation from profile

- public/locales/bg/common.json
- public/locales/en/common.json
- src/components/client/layout/Footer/helpers/FooterData.tsx
- src/components/client/layout/nav/DonationMenu.tsx
- Updated year of footer
- Placed campaign application page url to visible places
> chore: Add routes to campaign applications page

- src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.styled.tsx
- src/components/client/layout/nav/MobileNav/MobileNav.tsx
> ui: Use the correct component for MobileNav DonataButton
