src/components/shared/ConfirmationDialog.tsx
Issue: https://github.com/daritelska-platforma/frontend/issues/7
A sample confirmation dialog. Additional styles, props and tests can be added further when we have more clarity about the usage.
=> #7 Create ConfirmationDialog common component

.eslintrc.js, src/common/form/validation.ts, src/pages/api/timeout.tsx, src/pages/login.tsx
Type `any` is provides the ability skip strict type checks and may lead to problems in debugging
This PR enables a warning when we use `any` in the codebase while we're at the beginning of the journey and the codebase is small.
However sometimes is more convenient to use `unknown` instead of `any`.
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-explicit-any.md
=> Trigger warning when using any as type

src/components/chart/TeamPie.tsx
Still not perfect but at least if you turn from landscape mode to portrait, the pie renders back as before.
And now you can see most of the labels. On the others screens there is no change, they look fine as before.
=> Improve TeamPie on phone portrait mode

public/locales/bg/index.json, public/locales/en/index.json, src/components/index/IndexPage.tsx, src/components/index/sections/ActivitySection.tsx, src/components/index/sections/Jumbotron.tsx, src/components/index/sections/ProblemsToSolveSection.tsx, src/components/index/sections/SupportUsSection.tsx, src/components/index/sections/TeamChartSection.tsx, src/components/index/sections/TeamSection.tsx
- SEO tips by Ivelin Todorov
- Made some `h5` headings keep their style but be `h2` underneath 
- Responsiveness for couple sections on the homepage
- Made layout without gutters so the image goes full width
- Improved box sizing for activities
Before|After
---|---
=> Added markup according to seo instructions. 

.env.example, docker-compose.dev.yml, docker-compose.prod.yml, docker-compose.staging.yml, docker-compose.yml, kubernetes/README.md, kubernetes/cockroachdb.yaml, kubernetes/frontend-deployment.yaml, kubernetes/frontend-net-networkpolicy.yaml, kubernetes/frontend-service.yaml, kubernetes/podkrepi-dev-namespace.yaml, skaffold.yaml
added: skaffold configuration to enable native kubernetes development
added: cockroachdb as singlenode
updated: docker-compose.yml to allow running kompose which requires version 3.7
The change introduces skaffold config which makes it easier to have local kubernetes environment for developing and testing in similar to production environment. See the readme.md in ./kubernetes folder
It does not contain code changes.
none
cockroachdb
skaffold
=> added: skaffold configuration to enable native kubernetes developmen

src/common/form/validation.ts
Removed '-' from noNumbersRegex in order for the symbol to be allowed in Name and Last name text fields.
Screenshot:
=> Fixed name validation

src/components/index/sections/Jumbotron.tsx
Removed horizontal scrolling on homepage on mobile devices. 
The issue was caused by the larger font-size of the page title. Now it is 45px for mobile devices (under 600px):
=> Removed horizontal scrolling on homepage on mobile devices

src/components/index/sections/Jumbotron.tsx
Because the button was looking way bigger with the text on two lines and it didn't match the design
#160 
Changed the padding from theme.spacing(5) to theme.spacing(4) so that the text doesn't wrap now, but if more text is added to the button at a later moment it might still happen.
| Text was wrapping | Text is on one line now |
|![image](https://user-images.githubusercontent.com/61479393/114092457-97a23700-98c2-11eb-888e-94ed7ab4c2da.png)) | ![image](https://user-images.githubusercontent.com/61479393/114092565-b43e6f00-98c2-11eb-9aa5-524a6324eaba.png)
|
Tested it on all resolutions and  it doesn't break anywhere.
=> Reduced about us button padding

src/components/support-form/SupportForm.tsx
To be able to submit the form immediately after you either confirm or cancel the popup dialog.
#159
Previously when clicking the dialog buttons only the steps were advancing and no request was sent
Added a reference to the form with useRef() and used it to submit the form through the handleNewsletterDialogCancel/Confirm methods. There is a newer way to access the form through useFormikContext() hook, but that only works if the component you are accessing the hook from is a child of <Formik /> which the <SupportForm /> is not so I did it the old school way with innerRef.
| No request was sent | A request is now sent to the backend |
|https://user-images.githubusercontent.com/893608/114022480-7d446b00-987a-11eb-87b9-7df3369d06e8.mp4 | …
=> Submitting the support form through the newsletter dialog

frontend/Dockerfile
Fixes #233
Added `g++`, `make` and `python` to the `frontend` image to fix the failing Docker build.
=> 🐛 Fix failing frontend docker build

backend/module-campaigns/Dockerfile
Fixes #237
It seems that the Apple M1 + Docker + dotnet + gRPC combination is problematic. The issue is described into details here:
https://danielstoyanoff.medium.com/apple-silicon-docker-dotnet-grpc-is-that-compatible-8a05f1a71d89
Long story short - nuget tries to use arm64 `protoc` which causes segmentation fault on M1. The workaround is to install `protoc` manually inside of the container and use that instead of the one provided by nuget.
=> 🐛 Fix failing campaigns docker build on Apple M1

.env.example, README.md
- `COMPOSE_PATH_SEPARATOR` :   Customize path separator. COMPOSE_FILE supports multiple Compose files separated by a path separator ( on Linux and macOS the path separator is :, on Windows it is ; ). If set to ":" Windows based devs can compose without additional configs.
=> Windows compatibility.

.env.dev, .env.staging, .github/workflows/deploy-nightly.yml, CONTRIBUTING.md, README.md, kubernetes/README.md
Renamed .env.example to .env.dev and .env.dev to .env.staging as per #204  
Guidelines and config files are updated accordingly.
The fix was needed to clear the confusion which .env. file is used for what purpose.
.dev is for local development
.staging is used for nightly deployments to dev1.podkrepi.bg
changed symling to .env.dev and started the site with docker-compose - works as before
=> Rename .env files according to #204

.github/workflows/deploy-prod.yml
A job in the .github/workflows/deploy-prod.yml workflow which uses [Actions Status Discord](https://github.com/marketplace/actions/actions-status-discord) GitHub Action to update the #website channel in [our Discord server.](https://discord.com/invite/nZAeCb9YzP)
We need this change to follow the status of the deployment process in our Discord channel.
This PR addresses #220 
- `APP_DISCORD_WEBHOOK` :  this is the URL of the webhook attached to the #website channel (I will send it privately to @kachar so he can add it in the settings of the repo)
=> Job for posting production deployments in the #website channel

.env.dev, .env.example, backend/contact/Dockerfile, backend/contact/api/config/config.go, backend/contact/database/database.go, backend/contact/main.go, docker-compose.dev.yml, docker-compose.prod.yml, docker-compose.yml
Removed cockroach-lb from env.dev, now lb is used for staging and prod only.
The change was needed to because in dev mode lb is not needed and also used to clear some of the code that was passing through the LB while the rest was going directly to the node.
details: 
- The golang contact service was not loading environment variables correctly, only the default hardcoded ones
- golang reference updated from 1.15 to 1.16
- not-fixed: campaign service (.Net) still uses hardcoded db host in appsettings
Tested:
Using 'docker compose up' on local machine and manual check the web site works.
=> removed cockroach-lb from env.dev

frontend/src/components/common/Heading.tsx, frontend/src/components/index/helpers/chart/TeamPie.tsx
Using lifecycle method  and state for running the animation to re-render the pie chart on window resize.
Also we have on little change that we forgot to push with previous PR, discussed here: https://github.com/podkrepi-bg/frontend/pull/278#discussion_r656027096
We need this change introduced because we need responsive website.
Fixes known bug: #255
=> Update pie chart

sentry.client.config.js
At the moment all localhost errors are getting reported to Sentry and this burns up our limits. We need to enable Sentry only for staging/prod env.
=> Disable sentry reports for localhost

src/common/theme.ts, src/components/campaigns/CampaignTypeSelect.tsx
Closes #394
The Select component within a FormControl behavior has changed in mui5 and the initial conversion used a small hack to correct the vertical alignment of the Label. However this lead to an issue when the Select is focused.
This new fix played with the prop of the Select and it seems removing `variant="filled"` from the Label and the margin="dense" achieves behavior like in mui-4
|  ![grab199](https://user-images.githubusercontent.com/6075606/139522770-d292e0e6-1064-4ec1-99c0-556ed2779642.jpg) | ![grab200](https://user-images.githubusercontent.com/6075606/139522779-10a58b8e-bc70-4e75-8584-5e8f9ecbd8b5.jpg)  |
=> fix: mui-5 select props fix

src/common/theme.ts, src/components/campaigns/CampaignTypeSelect.tsx
InputLabel does not change color to error when a field has formi errors
Visit the Create Campaign form and then tab through the Campaign Type Select without entering any data, the label will keep a blue color, even though the Campaign field is required bu empty 
| ![grab202](https://user-images.githubusercontent.com/6075606/139633082-25c4897d-1f2c-465c-83fc-c463835e3ad2.jpg)|![grab205](https://user-images.githubusercontent.com/6075606/139632974-cc965b19-b705-494e-8d37-3840fe48e806.jpg)|
=> fix: Inputlabel error color from formik

README.md, package.json, yarn.lock
When setting up the project for the first time, I got the following error:
`error - ./src/styles/global.scss
Global CSS cannot be imported from files other than your Custom <App>. Due to th
e Global nature of stylesheets, and to avoid conflicts, Please move all first-pa
rty global CSS imports to pages/_app.js. Or convert the import to Component-Leve
l CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: src\pages\_app.tsx`
This article: https://medium.com/@sohinipattanayak/solution-global-css-cannot-be-imported-from-files-other-than-your-custom-app-while-creating-a-9ffd3e767f8e pointed out, that this is a bug specific to next@11.1.1 and recommended downgrading to 11.1.0. I upgraded to the latest version, which is 12.0.4, which appears to have had the bug …
=> Upgraded next to the latest version and fixed the windows symlink command in the README

src/components/auth/login/LoginPage.tsx, src/components/auth/register/RegisterPage.tsx
Skips our internal login and register forms and redirect the user straight away to Keycloak auth pages
=> Login and register directly on Keycloak

next-env.d.ts, package.json, yarn.lock
Problem reported by @YordanDobrev97
`Failed to compile.
./src/pages/_document.tsx:9:45
Type error: Type '() => any' is not a constructor function type.`
This was caused by the upgrade to nextjs v12.0.5 which brings wrong import of Document as per the screenshot below. The issue is officially fixed in Nextjs v12.0.6, so this pull request is upgrading to the latest v12.0.7
Tested by building and manually checking the site on localhost
=> fixed: broken Document import due to upgrade to nextjs 12.0.5. Now upgraded to 12.0.7

.github/workflows/test.yml, jest.config.js, package.json, yarn.lock
This PR fixes the "yarn test" failure by replacing babel-jest with the builtin nextjs jest integration as per https://nextjs.org/docs/testing#jest-and-react-testing-library
- removed node12 from the test matrix in the testing git action
- also reduced parallel job runs to 1, because the second job yarn step was failing when executed in parallel
Currently there is only one test CopyTextButton.test.tsx which passes successfully after the fix
=> Fixed jest tests by replacing babel-jest with the builtin nextjs jest

src/components/about/sections/PrincipleCard.tsx
Since we changed the background color of the website from light grey to white, the background had to be changed here too:
| ![Screenshot 2022-01-13 230509](https://user-images.githubusercontent.com/14351733/149409031-81188627-f1d2-4c8f-a6df-b5e1e0fca713.png) | ![Screenshot 2022-01-13 230406](https://user-images.githubusercontent.com/14351733/149409063-3c1d96c9-6fd1-4b73-96f4-783dc611c299.png) |
=> Change background color of Principles section in About Us page

CONTRIBUTING.md, src/pages/about-project.tsx, src/pages/about.tsx, src/pages/contact.tsx, src/pages/faq.tsx, src/pages/privacy-policy.tsx, src/pages/support.tsx, src/pages/terms-of-service.tsx
Еnabled static page generation by switching to getStaticProps for pages which don't load database content
The change is needed for enabling SEO for public pages and content which don't require login. Such pages are about us/about-project, faq, terms&conditions, etc. 
See the list of static pages marked with full circles on the build report below:
manual opening each affected page
=> Enable static pages generation at build time

src/components/layout/Layout.tsx, src/pages/about-project.tsx, src/pages/about.tsx, src/pages/contact.tsx, src/pages/faq.tsx, src/pages/privacy-policy.tsx, src/pages/support.tsx, src/pages/terms-of-service.tsx
This change enables static pages generation at build time, while the header is still loaded dynamically at runtime. 
- The dynamic header is imported as per the With No SSR section here: https://nextjs.org/docs/advanced-features/dynamic-import
- The static pages are marked with full dots on the below screenshots. 
manual on localhost only
=> Enable static pages with dynamic header

.env.local.example, public/locales/bg/common.json, public/locales/en/common.json, src/components/admin/AdminPage.tsx, src/components/admin/InfoRequestPage.tsx, src/components/admin/SupportersPage.tsx, src/components/layout/nav/AdminMenu.tsx, src/components/layout/nav/MainNavMenu.tsx
- added Admin menu, showing only when authenticated
- switched keycloak-realm to webapp-dev for local development mode
The admin menu is needed for grouping administrative activities
Manual login/logout and loading the admin page
=> Added Admin Menu

src/components/campaigns/CampaignForm.tsx, src/components/contact/ContactForm.tsx, src/service/restRequests.ts
We need to authenticate the people when we want them to submit their campaign
With this PR we introduce a simple way of adding keycloak token to the mutation requests.
Until now the mutation functions were constants and now we are defining them as hooks so we can use keycloak instance inside their body.
```tsx
const mutation = useMutation<AxiosResponse<CampaignResponse>, AxiosError<ApiErrors>, CampaignInput>({
mutationFn: createCampaign
})
```
```tsx
export const createCampaign: MutationFunction<AxiosResponse<CampaignResponse>, CampaignInput> =
async (data: CampaignInput) => {
return await apiClient.post<CampaignInput, AxiosResponse<CampaignResponse>>(
endpoints.campaign.createCampaign.url,
data,
)
}
```
```tsx
const mutation = useMutation<AxiosResponse<CampaignResponse>, …
```
=> Send person authentication to the backend on campaign creation

public/locales/bg/common.json, public/locales/en/common.json, src/components/layout/nav/PublicMenu.tsx
- Updated copyright text from ©2021 to ©2022:
- Change profile dropdown color links and hover effect:
=> Update copyright text, change profile dropdown color links

README.md
Changed a flag in the Symlink command for Unix systems
During initial setup the provided command with -h flag throws an error on Linux systems. The -n flag is more compatible with Linux systems and still works with Mac.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
**Before Screenshot**
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
**After Screenshot**
=> Changed -h flag Symlink to -n for better compitability.

src/components/admin/navigation/adminMenu.tsx
Added **missing link** to **coordinators** in admin drawer.
=> added missing link for coordinators to admin

src/components/about-project/sections/TechStack.tsx
- Adedd checkmark icons before the list items.
- Added icons before technology subheadings.
- Fixed subheadings' font-weight.
- Fixed spacings.
| ![image](https://user-images.githubusercontent.com/14351733/164531921-3f020bec-eeb0-48db-ac56-269fdaa4f09a.png)  | ![image](https://user-images.githubusercontent.com/14351733/164531975-d2928079-66c3-418c-8803-5f0fbe96aa2d.png) |
=> Fix Technologies section on About project page

.eslintrc.js, next-sitemap.js, package.json, public/robots.txt, public/sitemap-0.xml, public/sitemap.xml, src/pages/admin/documents/[id]/edit.tsx, yarn.lock
Having a sitemap is one of the requirements for good Search Engine Optimization mentioned in #46
Solved by adding next-sitemap package and configuring it accordingly. Admin and test pages will be skipped. Will generate the sitemap after each run of yarn build command.
Nothing visible for now.
Sitemap appears in /public
- `next-sitemap` : automated sitemap generator https://www.npmjs.com/package/next-sitemap
=> Added sitemap generator for SEO

src/components/campaigns/CampaignsList.tsx
When campaigns are loaded initially only 6 campaigns should be shown.
A button should be added and when it is clicked it should show all of the campaigns. When it is clicked again it should show less campaings(6 campaigns).
When they are less than 6 campaigns there is no button.
http://localhost:3040/campaigns
=> 720 feature add button to load more campaigns and set intially shown campaigns to 6.

src/common/theme.ts, src/components/common/FormFieldButton.tsx
Changed the styling of the inputs in the `muiTheme` we are using. 
The corners of the oneline input fields are now fully round and the corners of the mulitline input are more round than they were before
|![image](https://user-images.githubusercontent.com/61479393/166110842-0c83031b-6b12-46ae-bec7-440427ce6c59.png)|![image](https://user-images.githubusercontent.com/61479393/166110834-2208050c-6e10-4e89-b629-cc1cd28833b7.png)|
Went through many of the pages and didn't find any bugs whatsoever 🚀!
=> Add rounded corners to inputs on the theme

src/gql/campaigns.ts
Property uploadedById has been changed to personId in the api and requires change in gql type also. 
Details in https://github.com/podkrepi-bg/api/issues/227
=> Updated campaign file gql

public/locales/bg/common.json, public/locales/en/common.json, src/common/routes.ts, src/components/faq/contents/common.tsx, src/components/layout/nav/ProjectMenu.tsx
- Added Reports link in About Project menu (leads to '/npo/reports') :
- Fixed Reports link in FAQ page:
- Removed hardcoded URLs from FAQ page.
=> Add reports in About Project menu, fix reports link in FAQ

.env.local.example, src/common/theme.ts, src/components/campaigns/CampaignCard.tsx, src/components/campaigns/CampaignForm.tsx, src/components/campaigns/DonorsAndDonations.tsx, src/components/campaigns/InlineDonation.tsx, src/components/index/sections/CampaignsSection.tsx, src/components/index/sections/FaqSection.tsx, src/components/index/sections/ReadyToStartCampaignSection.tsx, src/components/index/sections/WantToHelpPodkrepiBg.tsx, src/components/layout/nav/PrivateMenu.tsx, src/components/layout/nav/PublicMenu.tsx
The current state of the buttons was pretty random and there were styling on top of the default button stylings. 
I have now changevdthe styles to be in tact with the UI Kit and in my opinion this way they look better.
This is the reference design:
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=38%3A3937
There are quite a bit of changes to the theme though and everything has to be looked at by QA if possible since there might be problems that arise from that.
|<img width="1109" alt="image" src="https://user-images.githubusercontent.com/61479393/167727719-4a8ef5ae-a986-4a18-ad65-dbca2f68d43f.png">|<img width="1176" alt="image" …
=> Add button hover states in the theme to correspond to the UI theme

src/components/auth/profile/DonationTab.tsx
- Removed last name from the greeting on Donation tab.
- Added coma after first name.
=> Fix greeting on Donation tab on Profile page

src/components/about/sections/HowEverythingBegin.tsx
The issue was caused by the incorrect id of the title.
=> Fix 'How everything begin' hyperlink on About Us page

src/components/about-project/sections/WhatIsDone.tsx
- Deactivated the architecture map link since it is not currently available. 
- Fixed title styles.
| ![Screenshot 2022-05-21 075440](https://user-images.githubusercontent.com/14351733/169636615-17cfa5fe-f712-4f1b-8a10-a4a729000605.png) | ![Screenshot 2022-05-21 080357](https://user-images.githubusercontent.com/14351733/169636620-04eae036-0355-456b-9b50-12f4dd7e7fe6.png) |
=> Fix minor FE issues on About Project page

src/common/util/roles.ts
The check for assigned roles was failing for users with Realm roles only. Fixed by checking for null object when collecting roles.
=> Fixed permission checks when logging with default users for local-keycloak

src/common/theme.ts, src/components/about-project/sections/TimelineItem.tsx, src/components/admin/navigation/AdminContainer.tsx, src/components/admin/navigation/AppBarMenu.tsx, src/components/admin/navigation/HoverMenu.tsx, src/components/auth/profile/ProfilePage.tsx, src/components/layout/nav/DonationMenuMobile.tsx
- Inherited the borderRadius styles from the theme - theme.shape.borderRadius (25px).
- Removed the style where it is not used.
- borderRadius is still inlined in Admin panel where it is not inherited from the theme, but has the default value of 25px.
- borderRadius: '50%' is saved, it makes the icons round.
=> Fix borderRadius styles

src/components/index/sections/Jumbotron.tsx
- Reduced the white space on the top of the section:
| ![Screenshot 2022-06-02 223638](https://user-images.githubusercontent.com/14351733/171724789-a5369b77-41a1-41c6-bffd-56b889657dba.png) | ![Screenshot 2022-06-02 223753](https://user-images.githubusercontent.com/14351733/171724903-58ca07c1-eebf-41a2-bea5-1f7899dc19e7.png) | 
- Fixed buttons' styles:
| ![Screenshot 2022-06-02 225021](https://user-images.githubusercontent.com/14351733/171726275-f74bf7b0-a4ff-490e-92e9-f53f3214d79b.png) |  ![Screenshot 2022-06-02 223828](https://user-images.githubusercontent.com/14351733/171725110-ff4916d2-1ae2-432e-b789-caa8caf3 …
=> Fix Jumbotron responsive styles

public/locales/bg/donations.json, public/locales/en/donations.json, src/common/routes.ts, src/components/bank-transactions-file/roles.ts, src/components/bank-transactions-file/types.ts, src/components/donations/AddBankTransactionsFile.tsx, src/components/donations/AddBankTransactionsFileForm.tsx, src/components/donations/grid/GridAppbar.tsx, src/components/file-upload/BankTransactionsFileList.tsx, src/gql/donations.d.ts, src/pages/admin/donations/add-bank-transactions-file.tsx, src/service/apiEndpoints.ts, src/service/donation.ts
The general idea is that when an admin of this site is give a file of bank transactions in a specific format, then he/she upload on the api and all of the donations which are inside this file will be checked and donations will be made. 
This pr is connected with 238.2 feature functionality for uploading a payment receipt and updating bank transactions/https://github.com/podkrepi-bg/api/pull/263/
The idea is to simplify the process and automatize it so it won't be done by hand.
[report-bank-transactions-files-for-testing.zip](https://github.com/podkrepi-bg/frontend/files/8890692/report-bank-transactions-files-for-testing.zip)
In order to test, you need to extract the files from the attached zip file, …
=> 739.1 feature functionality for uploading a payment receipt and updating bank transactions 

src/components/campaigns/grid/EditForm.tsx, src/components/campaigns/grid/EditPage.tsx, src/components/campaigns/grid/UploadedCampaignFile.tsx
When editing a campaign, the uploaded file list is not refreshed and leaves the impression the upload was not successful.
- fixed: invalidateFileList when Editing Campaign
- fixed: flashing 404 when loading CampaignEditPage
- fixed: deleting a single campaign file to not return to campaignlist
=> fixing campign file list not updated

src/components/pdf/Certificate.tsx
Amounts in PDF certificate are not formatted as money value
A donation of 20 lev results in 2000 in the PDF
=> Properly display amount in PDF certificate

package.json, src/components/campaigns/CampaignDetails.tsx, src/components/campaigns/CampaignInfo.tsx, src/components/campaigns/grid/CampaignGrid.tsx, src/components/campaigns/grid/CreateForm.tsx, src/components/campaigns/grid/EditForm.tsx, src/components/campaigns/grid/UploadedCampaignFile.tsx, src/components/pdf/Certificate.tsx, yarn.lock
Campaign description field should allow rich-text formatting as per https://github.com/podkrepi-bg/frontend/issues/845
Decided to add React Quill as one of the most popular wysiwyg editors and also low-code integration.
- added: react-quill as wysiwyg richtext editor with default toolbar
- cleanup and formatting
After
manual
- `dependency` : React Quill v2 (yarn add react-quill@beta)
=> add richtext editor for campaign description

src/components/campaigns/grid/CreateForm.tsx, src/components/campaigns/grid/EditForm.tsx, src/components/common/form/FormRichTextField.tsx
RichText editor in CreateCampaignForm was not showing errors and submit form button was not working.
Fixed by creating a custom error placeholder. Side improvement: extracted the ReactQuill editor as common component.
=> Fixed RichTextEditor for CreateCampaignForm

README.md, src/components/auth/register/RegisterForm.tsx, src/components/campaign-types/Form.tsx, src/components/campaign-types/grid/Grid.tsx, src/components/campaigns/CampaignFilter.tsx, src/components/campaigns/CampaignsList.tsx, src/components/campaigns/CampaignsPage.tsx, src/pages/admin/campaign-types/[id]/edit.tsx, src/pages/admin/campaign-types/create.tsx, src/pages/admin/campaign-types/index.tsx
Fixes: https://github.com/podkrepi-bg/frontend/issues/843
and improves CampaignList page
- removed wordy text on campaign list and reduced witespace
- campaigns are displayed in 4 columns on big screens
- fixed: admin page for editing CampaignType categories
| 
|<img width="1670" alt="Screenshot 2022-07-08 at 11 17 05" src="https://user-images.githubusercontent.com/91589884/177949243-4887ebeb-1aff-4edd-8af2-30de23a342a8.png">|
|<img width="850" alt="Screenshot 2022-07-08 at 11 21 22" src="https://user-images.githubusercontent.com/91589884/177949668-d86c67fa-6200-44ba-afa6-5792d0fd1e60.png">|<img width="774" alt="Screenshot 2022-07-08 at 11 20 46" …
=> Fixing CampaignTypes and Categories

src/components/campaigns/grid/CampaignGrid.tsx
Clicking on campaign reached amount in donations grid was opening new tab without token, so session was lost.
Links are made internal now.
=> fixed: links to campaign donations are internal now

src/components/one-time-donation/OneTimeDonationPage.tsx, src/components/one-time-donation/Steps.tsx
#906 
It was confusing for the donor that the screen is showing the big campaign picture when one-time-donation page is opened. It was fixed and now the page is positioned to the title on every step.
| ![before](https://user-images.githubusercontent.com/14825765/181182408-d5f27740-5ff9-4e72-a1b1-129ca424797b.PNG) | ![after](https://user-images.githubusercontent.com/14825765/181182432-fe37df51-5932-4970-aaf7-1b4624efb079.PNG) |
=> Fixed page positioning in donation workflow

src/common/util/money.ts
=> Changed thousand separators in BG money format

Dockerfile, Dockerfile.maintenance, manifests/base/deployment.yaml, manifests/base/maintenance.yaml
=> Containers and manifests hardening

src/components/about-project/FinanceReportPage.tsx
Links of the finance reports were swapped and the link for 2021 opened 2022 report.
=> Swap report links on finance page

src/components/index/sections/BetaPopUpDialog.tsx
The beta popup used to show on every page refresh. It now stores the setting into local storage so it is persisted across refreshes
=> Fix showing beta popup

src/components/one-time-donation/steps/FirstStep.tsx
Due to incorrectly set minimum OtherAmount field the Next button on First step did not allow proceeding with predefined amount.
This limit is removed now, it is checked on the Next Button validation anyway.
=> Fixed cannot pay with predefined amount

src/components/auth/login/LoginForm.tsx, src/components/auth/profile/DonationTab.tsx, src/components/one-time-donation/LoginForm.tsx
- fixed: campaign count in profile donation to be from unique slugs, because id is not returned from backend
- fixed: Google login on Second step of donation was missing onClick function - closes https://github.com/podkrepi-bg/frontend/issues/977
=> fixing google login and campaign counts

src/components/faq/contents/partnerships.tsx
Added link to partnership document - https://docs.google.com/spreadsheets/u/1/d/1TThb0VmaDJpM4mWV3BFLXquWQoL7AZ34o-ygANGU_UY/edit?usp=sharing
=> [Bug] FAQ/partnerships hyperlink  "Тук" not working

src/components/admin/AdminPage.tsx, src/components/admin/navigation/adminMenu.tsx, src/components/beneficiary/BeneficiaryTypes.ts, src/components/beneficiary/CreateForm.tsx, src/components/beneficiary/EditForm.tsx, src/components/campaigns/CampaignDetails.tsx, src/components/campaigns/grid/CampaignGrid.tsx, src/components/cities/CreateForm.tsx, src/components/cities/EditForm.tsx, src/components/companies/grid/CreateForm.tsx, src/components/countries/CountrySelect.tsx, src/gql/beneficiary.d.ts, src/gql/campaigns.ts
Several fixes of reported problems:
- admin menu renamed Payments to BankAccounts and reordered for convenience
- fixed: country selection when creating city, beneficiery and company
- fixed: when beneficiary is company, the company name needs to be displayed instead of person name
=> BankAccount, City and Company as Beneficient fixes

src/pages/admin/_middleware.ts, src/pages/api/auth/[...nextauth].ts, src/pages/profile/_middleware.ts
When the session expires and the user is on pages that require login, he is not redirected to login automatically and the site displays errors.
Fixed by adding check for token expiration in next-auth middleware for profile and admin pages.
=> added token expiration check in admin and profile page

src/components/campaigns/CampaignInfoOrganizer.tsx
Fixed organizer mail on campaign display page - instead of organizer it was wrongly displaying coordinator's mail.
=> fixed: organizer mail on campaign display page

package.json, src/components/campaigns/CampaignDetails.tsx, src/components/campaigns/CampaignInfo.tsx, src/components/campaigns/grid/CreateForm.tsx, src/components/campaigns/grid/EditForm.tsx, src/components/common/form/FormRichTextField.tsx, src/pages/_app.tsx, yarn.lock
Added image and video resize for the campaign description rich text editor. Also added a button for viewing html of the page for fine tuning the content. 
- "quill-blot-formatter": "^1.0.5",
- "quill-html-edit-button": "^2.2.12",
=> added: image/video resize and html edit in RichText editor

src/components/layout/nav/GenericMenu.tsx
The user can't scroll down if a dropdown menu is openned
Closing #1044 
The bug was noticed in the MUI github repository 
From the comments on the issue i found a solution on stackoverflow https://stackoverflow.com/questions/69065717/material-ui-menu-component-locks-body-scrollbar/71671897#71671897
Solved disabled scroll when a dropdown menu is opened
I solved the issue like on the Menu Component that is comming from MUI there is a property disableScrollLock and i set it to true
I checked the desktop pages if it's working everywhere and it's okay 
P.S
Sorry for the 3 commits i forgot to configure my git author name and email properly
=> 1044 bug hidden scroll bar on selected dropdown menu

src/components/layout/nav/AdminMenu.tsx, src/components/layout/nav/PrivateMenu.tsx, src/components/layout/nav/PublicMenu.tsx
The user can't scroll down if a dropdown menu is opened.I already fixed that in #1044 but then i wasn't having the backend installed.Now when i have it i noticed that the problem also appears when a user(PrivateMenu)/admin(AdminMenu) is logged in.Also it appeared when clicking on the user profile icon(PublicMenu) (obviously i didn't checked that).But now i fixed the issue in every dropdown menu.
Closing https://github.com/podkrepi-bg/frontend/issues/1047
The bug was noticed in the MUI github repository
From the comments on the issue i found a solution on stackoverflow https://stackoverflow.com/questions/69065717/material-ui-menu-component-locks-body-scrollbar/71671897#71671897
Solved disabled scroll when a dropdown menu is opened
I solved the issue like on the Menu Component that is …
=> Fixed the disabled scrolling when openning all dropdown menus

src/components/index/sections/CampaignsSection.tsx
Now that we have more campaigns, urgent campaigns need to appear on two rows.
Fixed by extending the slice from 4 to 8.
=> Urgent campaigns on two rows

src/components/auth/profile/MyCampaignsTable.tsx, src/components/campaigns/grid/CampaignGrid.tsx, src/components/campaigns/grid/GridActions.tsx
The change is required because the normal user shouldn't be able to delete their campaigns in my campaigns tab in the user's profile
I fixed the GridActions.tsx component in components/campaigns to accept one additional property via props - allowDelete, because this component is also used in *podkrepi.bg/admin/campaigns* and if the property is set to false the delete icon is not displayed and the opposite if the property is set to true. I also cleaned up the MyCampaignsTable component to not have additional unused code. I saw that there was Root property with styles, which was unused and i just deleted it, if this has some reason to be there just comment and i will fix it .
=> Removed the delete functionality from my campaigns tab

src/components/auth/profile/MyCampaignsTable.tsx, src/components/campaigns/grid/GridActions.tsx
I added a default value for allowDelete in the GridActions, so the allowDelete propery is per default set to false and in the admin CampaignGrid it set to true, while in the /profile/my-campaigns it's set to false per default (without setting it explicitly). The change was made as per recommendation of @kachar in #1073
=> Added default value for allowDelete in GridActions

public/locales/bg/common.json, public/locales/en/common.json, src/components/layout/Footer/Footer.tsx
=> Add SuperHosting partner in Footer

src/components/auth/profile/ProfilePage.tsx
There was a problem, that I saw from a message in discrod, that when the user in in https://podkrepi.bg/profile/[slug] in mobile view, not all tabs are visible. So basically the user can see only 3 of the 4 tabs, and there is no way that the user can see the fourth tab - the tabs are neither scrollable, nor they provide a button that can act like horizontal scrollbar.
I also changed the icon of my-campaigns section because they were kinda the same with the edit personal information icon( see the image below) 
I don't know if this is the perfect icon and I'm open to suggestions.
I followed the MUI documentation and implemented the Forced scroll buttons from there, because if you add just scroll buttons, they are available only in desktop mode, but not in mobile and that's not what we want. …
=> Made my profile tabs scrollable in mobile view

src/common/util/date.ts, src/components/auth/profile/PersonalInfoTab.tsx, src/components/auth/profile/UpdateBirthdateModal.tsx, src/components/common/form/FormDatePicker.tsx
Implements #1095 
The order of day/month between locales can be handled with localization, but the presentation differs by browser
e.g. in Chrome we have a `.` separator, while in Firefox we have `/` for the same locale. This has been worked around with a locale dictionary that maps the user lanugage to a specific date presentation format. Current formats include only `bg` and `en-US`, but others can be added as well.
The _update birthday_ modal now uses a MUI datepicker, as the presentation of the native `input type="date"` is not configurable. The mentioned datepicker lives in a separate convenience component in the `common/form` folder.
Before: (https://user-images.githubusercontent.com/48056945/202130942-c09d08b6-8d11-48b3-a7ed-218deaa78b30.gif)
After: 
For testing, users should …
=> Consistent date format in update birthday modal

src/components/auth/register/RegisterForm.tsx, src/components/one-time-donation/RegisterDialog.tsx, src/gql/donations.d.ts
Enable Terms and Conditions and GDPR validation on Register form so the user cannot continue without accepting both of the fields:
=> Enable Terms and Conditions and GDPR validation on Register form

README.md, src/components/one-time-donation/AnonymousForm.tsx, src/components/one-time-donation/FormikStepper.tsx, src/components/one-time-donation/LoginForm.tsx, src/components/one-time-donation/RegisterDialog.tsx, src/components/one-time-donation/Steps.tsx, src/components/one-time-donation/steps/SecondStep.tsx
The anonymous donation felt like it is not working properly. It was unpredictable.
**Now in order enable the button click next on the login step you have to either**:
* Be logged in in which case if you click next you will donate with your name
* Click the anonymous tab in which case it doesn't matter if you are logged in or not you will in both cases donate as *Anonymous*
| ![donation-anon-before](https://user-images.githubusercontent.com/61479393/202899426-af130c7e-a7b3-479e-b3e1-6ff9c7bab821.gif) | ![donation-anon-after](https://user-images.githubusercontent.com/61479393/202899430-06cd7156-fd4f-4cc6-af5d-37f98aace741.gif) |
Went through the donation flow in all 3 cases:
- Logged in normal
- Logged …
=> [Bug] You can click Next if you are both not logged and not anonymous

src/components/auth/login/LoginForm.tsx
Added border to google button in login page
Removed unused variable, which causes warning
Link to issue: [https://github.com/podkrepi-bg/frontend/issues/1113](url)
After:
=> 1113 Added border to button in login page

src/components/about/AboutPage.styled.tsx
| ![0](https://user-images.githubusercontent.com/14351733/203095468-4c81fa2a-9654-4e26-b385-83a4263e147b.png) | ![1](https://user-images.githubusercontent.com/14351733/203095516-3dbc845a-aa2e-42ab-bd0b-6b8bc62e8073.png) |
=> Fix the shape of the team avatars on About page

src/components/auth/changePassword/ChangePasswordForm.tsx, src/components/auth/profile/UpdatePasswordModal.tsx, src/components/auth/register/RegisterForm.tsx, src/components/common/form/PasswordField.tsx, src/components/one-time-donation/RegisterDialog.tsx
Hello and admiration for the project!
This is a fix for a tiny issue that I noticed while signing up for the platform.
Password managers or some browsers' built-in password features can generate and save passwords for you when they detect you're entering a new password - e.g. when you're registering, changing your password, etc.
They use the attribute `autocomplete` to do that. When it's set to `current-password`, they suggest existing stored passwords for you. When it's set to `new-password` they suggest generating and saving a new password.
[Mozilla docs on the subject](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)
In this project currently, all authentication forms use a default `PasswordField` component, which sets autocomplete to `current-password`.
This …
=> Fix missing autocompletion when entering a new password

src/components/campaigns/CampaignCard.tsx
Added component type Link to CardActionArea, because by default it uses anchor tag which refreshes the page and removes the locale from the route.
Issue link https://github.com/podkrepi-bg/frontend/issues/1153
=> 1153 Added component type Link to CardActionArea

src/pages/blog/[slug].tsx, src/pages/blog/index.tsx, src/pages/page/[slug].tsx
Closes #1167
Building the docker container with all needed variables in order to properly display the page. This process makes some of the missing env files undefined in the production build.
Replaced `getStaticProps` and `getStaticPaths` with `getServerSideProps`
This adds additional enhancement - the content is always fresh, and not cached between releases.
=> Switch static blog builds to dynamic content

src/common/hooks/campaigns.ts, src/components/campaigns/IrregularityPage.tsx, src/components/campaigns/ViewCampaignPage.tsx, src/components/common/CenteredSpinner.tsx, src/components/one-time-donation/OneTimeDonationPage.tsx, src/components/one-time-donation/Steps.tsx, src/pages/campaigns/[slug]/index.tsx, src/pages/campaigns/[slug]/irregularity.tsx, src/pages/campaigns/donation/[slug].tsx, src/pages/campaigns/index.tsx, src/pages/index.tsx, src/service/campaignTypes.ts, src/service/restRequests.ts
Addressed the issue specified here https://github.com/podkrepi-bg/frontend/pull/1152#issuecomment-1323969262 and #1166.
This returning of a `<NotFoundPage />` in the components that were changed seemed to cause the issue. Added a loader in it's place. This way though the case where `data` is empty is not handled, but we shouldn't get to this case since if the `campaigns/<slug>` does not exist the server should give us back a 404 and that will get handled by Next.
|![404-flash-bug](https://user-images.githubusercontent.com/61479393/203661274-b3cc8423-2e7c-4ebb-9064-97cdf7221143.gif)|![404-flash-fix](https://user-images.githubusercontent.com/61479393/203661295-3e99f903-9f72-4398-960a-170862d8eb30.gif)| …
=> 1166 - Fix flashing 404 page between page changes

src/components/layout/Layout.tsx
Closes #1170
When passing `metaTitle` it wasn't properly populated to the `og:title` property.
See no warning about `og:title` in 
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdev.podkrepi.bg%2Fblog%2Fyanika-novo-nachalo
=> Added the page title as default og title

public/locales/bg/vaults.json, public/locales/en/vaults.json, src/components/vaults/VaultSelect.tsx, src/pages/admin/expenses/create.tsx, src/pages/admin/transfers/create.ts, src/pages/admin/withdrawals/create.tsx
I can see that the ID's have been changed with names in previous task.
This PR fixes broken label translation
Issue link: [https://github.com/podkrepi-bg/frontend/issues/1011](url)
Before|After
---|---
=> 1011 Fixed broken translation

manifests/overlays/development/manual/deployment.patch.yaml, manifests/overlays/production/manual/deployment.patch.yaml
For security reasons it is important to always pull the container image prior to starting it. This was not done until now because the container was very big. Since we now have a decently sized container we can implement this change. Thanks @kachar
=> Always pull container in k8s

src/components/layout/AppNavBar.tsx, src/components/layout/Footer/LogoSocialIcons.tsx, src/components/layout/nav/AuthLinks/AuthLinks.styled.tsx, src/components/layout/nav/DonationMenuMobile.tsx, src/components/layout/nav/MobileNav/MobileNav.styled.tsx, src/components/layout/nav/MobileNav/MobileNav.tsx, src/components/layout/nav/ProjectMenuMobile.tsx
- Updated the logo on open mobile menu to be a Link.
- Updates styles as discussed with @swolf86:
Before|After
---|---
Before|After
---|---
- Fixed passHref warning in LogoSocialIcons component:
=> Update mobile menu styles

next.config.js
Closes #1187.
Removed a redirect in the `next.config.js`
Seems like the redirect bugged out the server side translations somehow. The redirect was supposed to redirect to `/profile/donations`, which is the first Tab on the page, but it does seem to work fine without the redirect.
Before|After
---|---
Tried logging out and in, clearing the cache, refreshing and it always seemed to translate.
Affected: `/profile` when you are logged in.
=> [Fix] - Translations on the profile page

src/common/form/validation.ts, src/components/auth/register/RegisterForm.tsx, src/components/one-time-donation/RegisterDialog.tsx, src/gql/donations.d.ts
Now when someone want to register and they dont fill up confirmation password, it will throw error message for users.
Closes #1119 
Before:
After:
Before:
After:
http://localhost:3040/en/register
Get on registration page: http://localhost:3040/en/register.
Try to fill up form without confirm password field.
Click on register button.
http://localhost:3040/en/register
=> 1119 - Confirm password in registration field is now required

.github/workflows/release.yml
Tests that run before deployment on Dev were failing. Fixed by adding secrets: inherit on the imported github workflow.
=> Fixing tests before deployment on dev

src/components/campaigns/CampaignCard.tsx, src/components/campaigns/InlineDonation.tsx, src/components/common/LinkButton.tsx
Added check if campaign status is completed and allowDonationOnComplete is false, to not redirect in donation page.
Closes #{1225}
Issue: [https://github.com/podkrepi-bg/frontend/issues/1225](url)
=> 1225 Added disabled property to CampaignCard and InlineDonation

src/components/index/sections/JoinPodkrepiBgSection/JoinPodkrepiBgSection.tsx, src/components/index/sections/TeamMembersSection/TeamMembersSection.tsx
Closes #1186
2 images on the homepage were not responsive.
Fixed them as per the examples provided by NextJS 
https://github.com/vercel/next.js/blob/canary/examples/image-component/pages/responsive.tsx
Team|Discord
---|---
Tested on all resolutions and images are responsive width width as the viewport until they hit the given `widths`
`index` - 'https://podkrepi.bg'
=> 1186 - fix homepage images to now be responsive

src/components/layout/AppNavBar.tsx, src/components/layout/nav/AuthLinks/AuthLinks.styled.tsx, src/components/layout/nav/AuthLinks/AuthLinks.tsx, src/components/layout/nav/DonationMenuMobile.tsx, src/components/layout/nav/MobileNav/MobileNav.styled.tsx, src/components/layout/nav/MobileNav/MobileNav.tsx, src/components/layout/nav/ProjectMenuMobile.tsx
* Fixed spacings and shrink effect on scroll:
Before|After
---|---
* Updated open mobile nav menu styles.
Default:
Before|After
---|---
Logged user:
Before|After
---|---
Admin:
Before|After
---|---
=> Update mobile nav menu styles

src/components/about/sections/AboutTheTeamSection/AboutTheTeamSection.styled.tsx
=> Fix discord team image on about page to be responsive

src/components/auth/forgottenPassword/ForgottenPasswordForm.tsx, src/components/auth/login/LoginForm.tsx, src/components/auth/profile/UpdateEmailModal.tsx, src/components/auth/profile/UpdateNameModal.tsx, src/components/auth/register/RegisterForm.tsx
When you enter email, firstName or lastName in one of the form in authorisation package and you accidentally put a leading/trailing space, it results into failed login because of invalid credentials. On most of the websites it's a common practice to ignore those "false" spaces when verifying the credentials, so we may apply it as well.
Closes https://github.com/podkrepi-bg/frontend/issues/1124
On most of the websites it's a common practice to ignore those "false" spaces when verifying the credentials, so we may apply it as well.
In order to fix that I had added trim to the end of the strings.
Unfortunately, in the issue it was suggested that we should add trim to the yup validation chain to fix the problem. This didn't work and it seems that there is a incompatibility between Formik and …
=> Fix fields in auth package not being trimmed automatically

src/components/auth/forgottenPassword/ForgottenPasswordForm.tsx, src/components/auth/login/LoginForm.tsx, src/components/auth/profile/UpdateEmailModal.tsx, src/components/auth/register/RegisterForm.tsx, src/components/common/form/EmailField.tsx, src/components/contact/ContactForm.tsx, src/components/irregularity/admin/grid/CreateForm.tsx, src/components/irregularity/admin/grid/EditForm.tsx, src/components/one-time-donation/AnonymousForm.tsx, src/components/one-time-donation/LoginForm.tsx, src/components/one-time-donation/RegisterDialog.tsx, src/components/person/grid/PersonForm.tsx
Extracted an EmailField component that includes the usual good practices for email fields - `type=email`, `inputMode="email"`, and `autoComplete="email"`. 
Closes #1155 
This makes the forms that use them a bit cleaner and enforces consistency.
Related to: #1120 
The impact of the changes is very small, it's more of a code refactor rather than a feature.
Some things to test are if the login forms don't behave unexpected due to the browser's built-in email validation. I tested that manually and it looks good.
All pages that have an email field
- `/forgotten-password`
- `/campaigns/[slug]/donation/[slug]` - the one time donation steps
- `/profile` and `/profile/[slug]` - the update email form in the personal info tab
- `/register`
- `/contact`
- `/admin/irregularities/create` and …
=> feat: extract and reuse email field as a separate component 

.vscode/launch.json, src/common/routes.ts, src/components/blog/BlogIndexPage.tsx, src/components/blog/BlogPostPage.tsx, src/components/layout/Layout.tsx, src/components/layout/LocaleButton.tsx, src/pages/blog/[slug].tsx, src/pages/blog/index.tsx
Closes #1262
Added pagination to blog articles. 
- Being that the blog was already server side rendered, I kept it that way.
- Current page number is in the url as a query param.
- Shows 9 articles per page (number chosen almost arbitrarily)
- When opening an article and then navigating back with the "go back" button, it goes back to the last visited blog page.
- Did some small SEO pertaining to the pagination.
- Can't click on prev or next buttons if already at first or last page, respectively.
- Changing the language (more specifically, when on pages other than the first page), preserves the current page.
- When opening an article and then navigating back with the "go back" button, it goes back to the last visited blog page. (Unless you switch the language once an article is opened.. …
=> 1262 - Add pagination to blog articles.

README.md, src/components/campaigns/CampaignForm.tsx, src/components/campaigns/grid/CreateForm.tsx, src/components/campaigns/grid/EditForm.tsx, src/components/common/form/FormRichTextField.tsx
It was reported the limit of 40k symbols is not enough so extending now.
- increased campaign description to 60K symbols
- added error helper on bottom of the richtexteditor too
=> extending campaign description

src/components/campaigns/CampaignsList.tsx, src/components/campaigns/CampaignsPage.tsx, src/components/index/sections/CampaignsSection/CampaignsSection.styled.tsx
Fix Campaigns section max width and alignment on Homepage and Campaigns page to be identical and responsive for bigger screens.
Homepage:
Campaigns page:
=> Fix Campaigns section max width and alignment on Homepage and Campaigns page

.github/workflows/build-nextjs.yml, .github/workflows/lint.yml, .github/workflows/playwright.yml, e2e/pages/web-pages/campaigns/campaigns.page.ts, e2e/pages/web-pages/campaigns/donation.page.ts, e2e/pages/web-pages/support.page.ts, e2e/tests/regression/support-as-member.spec.ts, src/components/one-time-donation/steps/FirstStep.tsx
There seems to be some issues with e2e tests failing, because of `checkURL` problems.
I also ran into problems locally, where the `<Collapse>` MUI animation would not unmount a component on exit and there were cases where playwright was trying to access elements that were hidden.
For the installation of the dependencies seems like without running `yarn install --immutable` there are resolutions errors sometimes.
Found some people also having the same problem and seems like having --immutable in CI actions is a better approach
https://github.com/redwoodjs/redwood/issues/4822#issuecomment-1072737065
=> Fix - e2e `checkURL` tests failing unexpectedly

public/locales/en/one-time-donation.json
Closes #1244 
Before|After
---|---
1. Switch the language
{{local}}/campaigns/donation/{{slug}}
=> en/one-time-donation.js: Swap the places of {{totalAmount}} and {{amount}}

e2e/tests/regression/donation-flow/anon-donation-fixed.spec.ts
Fixing the e2e tests for fee calculations which started failing due to swapping amount placeholders in english translation text.
=> Fixing e2e tests after english text swap of amounts

manifests/base/deployment.yaml
Recently some deployments were failing on readiness healthcheck with 503 service not available.
To give more time to start, this PR adds startupProbe with up to 2min (12 attempts per 10sec) before enabling the readiness and startup probes.
=> Added startupProbe for Kubernetes

src/test/helpers/stripe-fee-calculator.test.ts
Closes #1358 
This PR closes the above mentioned issue, which results to a better user experience.
1. Switch between wanting to cover and not wanting to cover the fee. Stripe's fee should be the same.
campaigns/donation/{slug}
In case of a merge the appropriate change should also be done to the [backend](https://github.com/podkrepi-bg/api/blob/f11d5223a991af47e68b953c16161ca6ccf1c3ad/apps/api/src/donations/helpers/stripe-fee-calculator.ts#L50)
=>  Change formula to calculate Stripe's fee

src/components/admin/donations/AddBankTransactionsFileForm.tsx, src/components/admin/donations/Form.tsx
- MenuItems Fields in `admin/donations/create` page are not responsive. When button in the admin menu for manual donation page is clicked nothing happens.
- File bank uploads routes user to the campaign page instead of the donation page when it is canceled. In my opinion this is not intuitive . This PR fixes the route.
Currently, the value doesn't change when someone clicks on it:
After the change, clicking on the element now changes the value:
=> MenuItems fields in manual donation are not responsive

src/components/admin/donations/Form.tsx, src/gql/donations.d.ts
This PR address this comment  https://github.com/podkrepi-bg/api/pull/447/files#r1114709693
In order to unify CreateBankPaymentDto and CreateManyBankPaymentsDto in the backend, I had added createdAt field in manual donation.
API change: https://github.com/podkrepi-bg/api/pull/451
Before
After:
=> Add createAt field for manual donation

public/locales/bg/common.json, public/locales/en/common.json
Updated the year in the Footer from 2022 to 2023 for BG and EN:
Before|After
---|---
=> Update the year in the Footer

src/common/hooks/donation.ts
Since there are problems with connection to Stripe and sometimes 2 or 3 requests are required before a checkout session is created successfully ([detailed issue here](https://github.com/podkrepi-bg/api/issues/463)), retry logic would be useful.
Tested with a failed request locally and the logic works as described in the `retry` method
`/campaigns/donation/{slug}`
=> stripe-connection-bug - add retry logic to the donation mutation

src/common/util/roles.ts
The restrictions were too tight and we were not considering an admin user as such in some cases.
We can have resource_access OR realm_access and still be an admin.
=> Admin user not treated as such on the frontend

src/components/client/one-time-donation/Steps.tsx
Closes #1133 
Due to the inverting the result of isLogged(), the initial value of isAnonymous is always true, when user is not logged in.
=> one-time-donation/Steps.tsx: Fix isAnonymous initial value

public/locales/bg/campaigns.json, public/locales/en/campaigns.json, src/components/client/campaigns/DonorsAndDonations.tsx, src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.tsx, src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignsSection.styled.tsx, src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.styled.tsx, src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.tsx, src/components/client/index/sections/CompletedCampaignsSection/helpers/CompletedCampaignsCaroucelSettings.tsx
- Update money representation on Active and Completed campaigns.
- Add gradient on Completed campaigns in order to make the title more visible.
- Fix Active campaign section cutting.
=> Update Active and Completed campaigns on Homepage

src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.styled.tsx, src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.tsx, src/components/client/index/sections/CompletedCampaignsSection/helpers/CompletedCampaignsCarouselSettings.tsx, src/components/client/index/sections/PlatformStatisticsSection/PlatformStatisticsSection.styled.tsx
Added minor updated on Completed campaigns carousel on Homepage:
- Changed mobile breakpoint from 500 to 600 to fit MUI small breakpoint.
- Removed the horizontal scroll on mobile devices (caused by invisible arrow buttons).
- Extracted styles in the corresponding file.
- Removed side spacings for the mobile carousel.
=> Update Completed campaigns carousel

src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.tsx, src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.styled.tsx, src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.tsx
Hide sum fraction from Active and Completed campaigns on Homepage.
=> Update money representation for Active and Completed campaigns on Homepage

src/common/hooks/donation.ts, src/components/client/one-time-donation/steps/FirstStep.tsx
There was request for campaign specific default donation amounts for Peter Zhotev campaign.
To accomodate this, now the default donation amounts are hardcoded in frontend.
Previously they were read dynamically from Stripe and were valid for all campaigns. 
TODO: Need to add campaign specific config for donation amounts in database
=> added hardcoded campaign specific prices

src/components/client/index/sections/PlatformStatisticsSection/Statistics/Statistics.tsx
Getting total count of donation was loading all of them on frontend.
Now optimized by asking only for 1 donation, which still returns totals.
=> reduce statistics size by asking only one donation from history

src/common/util/expenseFileUrls.ts, src/components/client/campaigns/CampaignPublicExpensesGrid.tsx
Closes #1417 
This PR contains changes which would allow to open the expense file in new tab, rather than download it, as well as:
-Significantly improves the the overall expense grid layout.
-Fixes an issue on smaller viewports which makes the cell's overlapping with one another.
-Fixes an issue where the expense description is clipped, on smaller viewports.
Before|After
---|---
=> Campaign expenses improvement

src/pages/_app.tsx
We want to measure the memory use of the donation notification popups when using socket io.
Switching them off now.
=> temporary switched off donation notification popups

src/common/util/notificationClient.ts, src/components/client/layout/NotificationSnackBar/NotificationSnackBar.tsx, src/service/visibilityApi.ts
Closes #1454 
The current websocket configuration, creates a new websocket client, for every SSR generated page. Since those clients are technically active, they are never cleaned up, thus resulting in memory leak. This change makes it so, a new web socket connection is created only on first render of the component.
1. Start visiting different pages randomly
2. Observe the current websocket clients, in the Socket object _(you can console.log the client arg from [handleConnection](https://github.com/podkrepi-bg/api/blob/master/apps/api/src/sockets/notifications/gateway.ts#L21))_ . The total amount of active clients can be found in Socket.adapters.sids
3. The size of sids should remain 1, per browser window
=> notificationClient: Establish ws connection only on client render

src/components/admin/donations/grid/Grid.tsx, src/components/admin/donations/grid/RenderEditBillingEmailCell.tsx, src/gql/donations.d.ts
Targets [podkrepi-bg/api#500](https://github.com/podkrepi-bg/api/issues/500)
Currently billingEmail is used to link all anonymous donations to a specific user profile. Unfortunately when user donates via bank transaction, and prefers the donation to be anonymous, there is no way to link that donation to user's profile. This commits allows billingEmail to be either set or edited manually, thus linking anonymous donations to user's profile
1. Open admin panel -> Дарения
2. Select specific donation, then go to Billing Email field and click the edit button
3. Select the profile to the user who will be associated with that anonymous donation
4. Click the save button
=> donations/grid: Allow admins to edit billingEmail

src/components/admin/InfoRequestGrid.tsx, src/components/admin/SupportersGrid.tsx, src/components/admin/cities/grid/CityGrid.tsx, src/components/admin/countries/grid/CountryGrid.tsx, src/components/admin/donations/grid/Grid.tsx, src/components/admin/expenses/grid/Grid.tsx, src/components/admin/irregularity/admin/grid/Grid.tsx, src/components/admin/organizers/grid/Grid.tsx, src/components/admin/transfers/grid/Grid.tsx, src/components/client/campaigns/CampaignPublicExpensesGrid.tsx, src/components/common/person/grid/Grid.tsx
Prior to updating the datagrid package, some tables hid the id field. This commit brings back this behavior
=> Datagrid: Hide id fields after datagrid v6 update

src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.styled.tsx, src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.tsx
- Align action buttons to the left.
- Reduce campaign card height for larger mobile devices (540px).
=> Add UI fixes on campaign cards on Homepage

src/components/admin/campaigns/grid/BeneficiarySelect.tsx, src/components/admin/campaigns/grid/CoordinatorSelect.tsx, src/components/admin/campaigns/grid/OrganizerSelect.tsx
https://github.com/podkrepi-bg/frontend/issues/1465
=> change select menus with Autocomplete component

public/locales/en/expenses.json, src/components/client/campaigns/CampaignPublicExpensesGrid.tsx
Fixes the filtering on type and amount fields
Closes # Reported in discord
=> CampaignPublicExpensesGrid: Fix type and amount filtering

public/js/hotJarLib.js, src/common/hotjar/HotJar.tsx, src/components/client/campaigns/CampaignsPage.tsx, src/components/client/campaigns/ViewCampaignPage.tsx, src/components/client/index/IndexPage.tsx
Injects HotJar library needed to generate heatmap
1. Go to index or /campaigns page and Load DevTools(Right click -> Inspect or F12).  To check if it loads on specific campaign, edit the condition inside `ShouldIncludeHotJar` to include slug from local enviroment.
2. Check if the `<head>` element includes the hotjar script.
=> Inject hotjar script

src/components/admin/AdminPage.tsx, src/components/admin/InfoRequestGrid.tsx, src/components/admin/SupportersGrid.tsx, src/components/admin/bankaccounts/grid/BankAccountsGrid.tsx, src/components/admin/benefactor/grid/Grid.tsx, src/components/admin/cities/grid/CityGrid.tsx, src/components/admin/coordinators/grid/CoordinatorsGrid.tsx, src/components/client/auth/profile/MyCampaignsTable.tsx, src/components/client/auth/profile/MyDonatedToCampaignsTable.tsx, src/components/client/auth/profile/MyRecurringCampaignsTable.tsx
autoHeight and autoPageSize shouldn't be used at the same time. By doing so this causes the data grid to constantly rerender 
ref: https://mui.com/x/react-data-grid/pagination/#automatic-page-size
Closes #1497
=> miu-DataGrid: Remove conflicting properties when using DataGrid

src/components/admin/partners/helpers/partnersData.ts
Closes https://github.com/podkrepi-bg/frontend/issues/1501 
The image was not displayed correctly due to a wrong path.
https://podkrepi.bg/img/partners/crossroads.svg - unavailable
https://podkrepi.bg/img/partners/crossRoads.svg - available
=> Fix image path of crossRoad partner

src/components/client/index/sections/MediaSection/MediaSection.styled.tsx, src/components/client/index/sections/PartnersSection/PartnersSection.styled.tsx
Replaced Link with ExternalLink in order to open in new tabs partners' websites on Partners carousel and articles on Media carousel.
=> Open Partners' websites and Articles in new tabs

src/components/admin/donations/grid/RenderEditBillingEmailCell.tsx, src/components/admin/donations/grid/RenderEditPersonCell.tsx, src/components/common/person/PersonAutoCompleteFilter.ts
This PR provides a fix for an issue, which made associating a certain donation to user impossible, when billingEmail field is null, as well as extending the autocomplete filter of the donor field, to look for both firstname and email.
Closes Reported in discord
=> admin/donations: Fix not being able to link user to donation if billingEmail is null

src/components/admin/InfoRequestGrid.tsx
Paging was not visible
Before:
After:
=> info-requests - added styles

src/components/client/campaigns/CampaignCard.tsx, src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.tsx
In some cases campaigns are marked as completed, due to their end date being reached, while the target amount has not been raised. 
This commit checks if the target amount has been raised, before showing the successfull tag.
Note:
This is a temporary solution until, a more descriptive campaign statuses are implemented.
=> [TEMP] Don't show successfull tag if campaign has not reached 100%

src/common/util/useCurrentPerson.ts, src/components/client/auth/profile/ProfilePage.tsx
In some cases the keycloak session expires before the client session, which results in user not being able to access account's data such as donations and profile information.
Note: 
We should probably re-think how to handle the client sessions better, but until then this should do.
Closes Reported in discord
1.Login in the [local enviroment](http://localhost:3040/login)
2. Go to [local keycloak server](http://localhost:8180/auth/) -> Administration Console ->Credentials should be user:admin, pw:admin ->webapp
3. Go to Session and click Logout All
4. Return to the logged user in [podkrepi.bg local enviroment](http://localhost:3040)
5. User should be logged out, due to session expiration
=> [TEMP] Signout user on unauthorized response

src/common/util/htmlSanitizer.ts, src/common/util/htmlUtils.ts, src/components/client/campaign-news/CampaignNewsList.tsx, src/components/client/campaign-news/SingleArticlePage.tsx, src/components/client/campaign-news/utils/getArticleHeight.ts, src/components/client/campaign-news/utils/scrollToTop.ts, src/components/client/campaigns/CampaignNewsSection.tsx, src/components/common/QuillStyleWrapper.tsx, src/components/common/form/FormRichTextField.tsx
List of changes:
1. Quill Editor: Fixed alignment of video and image being removed, when submitting .
2. CampaignNewsList: Fixed news layout being unresponsive.
3. Extracted the current Quill styling into separate component. This will be necessary, in order to keep the formatting of the currently added campaigns/campaign news, in case we drop the React Quill(issue #1503).
4. Whitelisted the iframe tag from DOMPurify. 
5. Implemented a function, which adds the `loading="lazy"` attribute to the iframe. This function, also allows to separate the iframe from, the rest of the HTML content, which might be needed in the future, when implementing the new campaign page ([ref](https://cdn.discordapp.com/attachments/779339122556796979/1133760880635564193/Screenshot_2023-07-26-14-59-15-817_com.figma.m …
=> SQUASH: Campaign news layout improvements

src/components/client/campaign-news/CampaignNewsList.tsx, src/components/common/QuillStyleWrapper.tsx
-Updated the font properties according the design specs, 
-Set max-width of container to 1200px, according to design specs
-Removed redundant properties.
Reference:
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?type=design&node-id=18746-56853&mode=design&t=1QqRtTdJE4fNuQNI-0
=> campaign-news: Fix styling according to design spec

src/components/client/one-time-donation/FormikStepper.tsx, src/components/client/one-time-donation/Steps.tsx, src/components/client/one-time-donation/helpers/donateSession.ts, src/components/client/one-time-donation/helpers/stepperContext.ts
Saves the selected values from formik inside sessionStorage, to prevent data loss, on page reload/refresh.
The values are saved until either successful donation has been made, or until the browser tab has been closed.
Closes #1260 
1. Select campaign, and click Donate buton.
2. Complete a few donation steps, and reload the page.
3. The selected values from donation flow, should be saved
=> Save donation flow inside sessionStorage

src/common/hooks/campaigns.ts, src/components/client/campaigns/ViewCampaignPage.tsx
In some cases, the url of the campaign, is invalid due to some typos being made. And since no data is coming from the server, the only thing the user sees, is a spinner going on forever. 
Fix this by rendering NotFoundPage, if the server has returned an error
Closes N/A
Improves UX
=> ViewCampaignPage: Show page not found on wrong slug

package.json, sentry.edge.config.ts, yarn.lock
* Updated the `@sentry/nextjs` module to latest version - 7.61.0.
* Added sentry.edge.config.ts as per the documentation: https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/
Closes #1395
Documentation:  https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/
`@sentry/nextjs`|`v7.21.1`|`v7.61.0`| Latest version as of Aug 1, 2023
=> Update @sentry/nextjs module to 7.61.0

src/components/client/one-time-donation/AnonymousForm.tsx, src/components/client/one-time-donation/OneTimeDonationPage/OneTimeDonationPage.tsx, src/components/client/one-time-donation/steps/SecondStep.tsx
Additional fixes for session storage
=> OneTimeDonationPage: Render DonationStepper only on client

src/common/hooks/campaigns.ts, src/components/client/campaigns/CampaignProgress.tsx, src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignsSection.tsx, src/pages/index.tsx
Needed to update the query state from prefetchQuery on the client. Improves loading time significantly.
-hook/campaigns:Remove staleTime from the useCampaignList.
Showing stale data, might confuse donors, as they expect their donation to be shown immediately.
=> pages/index.tsx: Dehydrate query client

src/common/hooks/campaigns.ts
Necessary data is prefetched on the server, and since campaign's data is no longer considered stale, it results in 2 queries to the server being made.
Due to the call of useCampaignList, the campaigns are being reordered twice - once on the server, once on client load, which makes it unpleasant for the users.
=> hooks/campaigns.ts: Disable useCampaignList on client

src/components/client/one-time-donation/LoginForm.tsx
Before|After
---|---
Related to https://github.com/podkrepi-bg/frontend/issues/1560
=> Add Forgotten password on Login form on donation

src/components/client/layout/AppNavBar.tsx
Hidden component has been deprecated in MUI v5.
This change also improves the rendering of app navbar by removing the layout shift caused by the hidden component.
Reference
https://mui.com/material-ui/migration/v5-component-changes/#hidden
=> layout/AppNavbar.tsx: Remove Hidden component

src/components/common/form/FormRichTextField.tsx
Until we figure out why it crashes on prod builds.
Closes Reported in discord
Loading MDXEditor, causes the whole `FormRichTextField` component to crash when lazy loading it.
=> [TEMP]: Drop MDXEditor for now

src/components/client/campaigns/CampaignCard/CampaignCard.tsx, src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.tsx, src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.tsx
Use next/image component for campaign card images.
Closes #{issue number}
As of now we don't have a strict policy on image sizes for campaign's cards. This result in scenarios where a 1MB images are used, which affects both the user experience, and web vitals stats tremendously, as it takes some time before they are downloaded by the client.
The easiest way to solve this, is to use Next's Image component which provides, out of the box optimizations to reduce image size(such as automatically converting it to webp, and compressing it).
=> Use next/image component for campaign images

src/components/admin/bank-transactions/grid/Grid.tsx
Closes #1588 
* Bank transactions are now sorted in descending order (by transaction date).
=> Sort bank transactions by descening date

src/components/client/campaigns/CampaignCard/CampaignCard.tsx, src/components/client/campaigns/CampaignProgress.tsx, src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.tsx, src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.tsx, src/components/client/layout/AppNavBar.tsx, src/components/client/layout/Footer/LogoSocialIcons.tsx, src/components/client/layout/nav/DonationMenuMobile.tsx, src/components/client/layout/nav/MobileNav/MobileNav.tsx, src/components/client/layout/nav/ProjectMenuMobile.tsx, src/components/client/layout/nav/PublicMenu.tsx
Apparently  I've missed testing the `<Image/>` adoption on some widths. This change should improve the situation for now.  
Closes #1591 
Fixing a layout bug
=> index: Fix layout break on smaller viewports.

src/components/common/QuillStyleWrapper.tsx
MDXEditor doesn't add the ql-video class to the iframe element, resulting in layout break on smaller viewports.
=> QuillStyleWrapper: Make iframe responsive when inserted via MDXEditor

src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.styled.tsx, src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.tsx
- Wrap the whole content of completed campaign's card with a link. Currently on production only the image is a link.
- Update the hover effect to cover the whole card, not only the image.
=> Wrap Completed campaign card's content with link, update hover effect

public/locales/bg/person.json, public/locales/en/person.json, src/components/admin/organizers/grid/DeleteModal.tsx, src/components/common/form/CheckboxField.tsx, src/components/common/person/PersonForm.tsx, src/components/common/person/grid/CreateForm.tsx, src/components/common/person/grid/CreatePage.tsx, src/components/common/person/grid/EditForm.tsx, src/components/common/person/grid/EditPage.tsx, src/components/common/person/grid/PersonForm.tsx, src/gql/beneficiary.d.ts, src/gql/person.d.ts, src/service/organizer.ts
Allow setting user as a coordinator, organizer and/or beneficiary from the user edit/create form.
Currently only coordinator and organizer are implemented!
Issue #1579 
Before
After
=> Mark user as Coordinator, Organizer and/or Beneficiary

src/components/client/index/sections/PlatformStatisticsSection/Statistics/Statistics.styled.tsx
- Updated the font size of 'дарени лева' (from 14px to 16px) to be identical to 'кампании', 'дарения' and 'дарители'.
- Removed the spacing at the beginning of 'дарени лева'.
Before|After
---|---
=> Update Statistics styles (Homepage)

.eslintrc.js, .prettierignore, .vscode/tasks.json, README.md, public/locales/en/admin.json, src/components/client/irregularity/helpers/irregularity.types.ts, src/components/common/person/PersonAutoCompleteFilter.ts, src/components/common/person/grid/CreateForm.tsx, src/components/common/person/grid/EditForm.tsx, src/gql/person.d.ts, tsconfig.json
Closes https://github.com/podkrepi-bg/frontend/issues/1006
Depends on: https://github.com/podkrepi-bg/api/pull/555
The requirement is when adding a person through the AdminUI for the purpose of being beneficiery it should not ask for email, since not every beneficiery has email actually.
Changes:
- made email optional when creating person as Beneficiery
- added build tasks
- formatting fixes
=> beneficiery without mail

src/components/common/form/FormRichTextField.tsx
Disable the MDXEditor integration. Restore Quill.
The editor does not support the following requirements:
- Colors
- Text alignment
- Image and video alignment
=> Disable MDXEditor integration

src/components/client/index/sections/PlatformStatisticsSection/Statistics/Statistics.tsx
Closes Issue #1614
- What problem are you trying to solve?
Donated money value in Statistics section is not rounded correctly when the value of stotinki ends with 0.
For example, if the stotinki amount is '10', the display value is '1'.
- How did you solve the problem? 
Specify the length of fractional part of 'donatedMoney' amount and padded it with zeros in order to meet the specified length, then display the fraction.
Before|After
=> Rounds correctly Donated money value in Statistics section

src/components/admin/partners/Partners.styled.tsx, src/components/admin/partners/PartnersSlider.tsx
Update Guarantors slider arrows on Partners page for mobile devices:
=> Update mobile Guarantors slider

public/locales/bg/about-project.json, public/locales/en/about-project.json, src/components/client/about-project/FinanceReportPage.tsx
Added finance report for 2022 on Finance report page:
=> Add Finance report for 2022

src/components/admin/donations/grid/Grid.tsx
With https://github.com/podkrepi-bg/frontend/pull/1635 refund functionality was introduced. This functionality is only available for stripe donations. This PR improves UI experience  and shows  refund button only for the successful stripe donations.
=> Add check to refund stripe donations only

.github/dependabot.yml, .github/workflows/release.yml
- added dependabot to update github actions automatically
- added run-name for Release github workflow to better distinguish it in the actions list
=> github actions update

public/locales/bg/campaigns.json, public/locales/en/campaigns.json, src/components/client/campaigns/CampaignInfo/CampaignInfoStatus.tsx
Translate accurately the campaign type when a campaign page is opened.
The campaign type does not translate on language change.
- Additional Bulgarian translations has been added.
- Uses different prop (campaignType.slug instead of campaignType.name) to display a campaign type.
Campaign page
=> [Campaign page] Aligns campaignType translation

.github/workflows/tests.yml
They are failing today by some reason.
This blocks any changes on production.
=> Temporary disable k8s scans tests

src/components/client/campaigns/CampaignDetails.tsx
Prettier seems to have added brackets in a place that was not needed
=> client/campaigns: Fix expenses chart and table not showing

src/components/admin/vaults/VaultSelect.tsx, src/components/admin/vaults/grid/Grid.tsx, src/gql/vault.d.ts
-Added sum of succeeded withdrawals to the vault's data
-Vault's grid shows campaign title instead of campaign id
-When creating withdrawal show only vaults of selected campaign
=> src/admin: Vault and Withdrawals improvements

src/common/hooks/campaigns.ts, src/components/client/campaigns/CampaignFilter.tsx, src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignsSection.tsx, src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.tsx, src/components/client/index/sections/PlatformStatisticsSection/Statistics/Statistics.tsx
When useCampaignList is called in the admin panel it uses cached value, and when the cached value expires, users won't be able to see the list of campaigns.
=> hooks/campaigns: Disable useCampaignList only if data is prefetched

src/components/client/pdf/Certificate.tsx, src/pages/api/pdf/certificate/[donationId].tsx, src/service/auth.ts
Anonymous donations don't have personId to find them by users, thus get donor's names from session token.
REQUIRED keycloak changes:
Go to keycloak->webapp->Client scopes -> profile -> mappers -> Create 
Fill the fields with the following values:
Name: company
Mapper Type: User Attribute
User Attribute: companyName
Token Claim Name: company
Claim JSON type: String
Save
=> pdf/Certificate: Get donor's names from session token

src/components/client/campaign-news/secured/CreateForm.tsx, src/components/client/campaign-news/secured/EditForm.tsx
Not currently used, and causes confusion
=> campaign-news: Remove sourceLink field

src/components/common/form/QuillEditor.tsx
When uploading video from youtube, on some occasions the requests could be blocked from youtube's course policy. For such occasions always convert copied youtube links, to youtube embed.
=> QuillEditor: Use youtube embed URL if source is from youtube

src/components/client/campaigns/DonorsAndDonations.tsx, src/gql/campaigns.ts
When a bank transaction is imported from IRIS, we receive only the date of the transaction, and not the hours. Due to that it was decided that returned donations will be ordered by the updatedAt field, rather than createdAt.
In order to correctly represent, the data coming from database, we need to use updatedAt field on the front-end to show how much time has passed since donation was made, otherwise the lack of hours of bank donations makes the donation list to appear unordered.
Example of the mentioned problem:
Cleaned up some commented code.
=> DonorsAndDonations.tsx: Show updatedAt field as date instead of createdAt

src/components/client/index/sections/TeamMembersSection/TeamMembersSection.tsx, src/components/client/notifications/CampaignSubscribeModal.tsx, src/components/client/notifications/GeneralSubscribeModal.tsx, src/components/client/notifications/SubscriptionPage.tsx
When selecting `On the profile one` button from the notifications modal, crash occurs, due to email not being provided to the backend. Use logged in user's email from the session token, when `On the profile one` button is clicked.
Removed some unused imports.
=> client/notifications: Fix crash when selecting profile's email

src/components/client/index/sections/SubscriptionSection/SubscriptionSection.styled.tsx, src/components/client/index/sections/SubscriptionSection/SubscriptionSection.tsx
=> Update Subscription section UI

src/components/client/layout/nav/DonationMenuMobile.tsx, src/components/client/layout/nav/ProjectMenuMobile.tsx, src/components/common/StyledAccordion.tsx
Since the last commit, it was observed that there is still very minor difference in colors, between different navigations.
=> layout/nav: Fix text color inconsistencies in mobile navigations

src/components/client/notifications/SubscriptionPage.tsx
The issue was caused by handleSuccess not being called, on successful response.
=> SubscriptionPage.tsx: Fix showing error on successful subscription

src/components/admin/donations/grid/Grid.tsx, src/service/apiEndpoints.ts
Allow to update donation amount, to received payment amount.
=> admin/donation: Allow to sync donation amount with payment amount

src/components/admin/donations/grid/Grid.tsx, src/components/admin/payments/grid/Grid.tsx, src/components/admin/payments/grid/GridFilters.tsx, src/gql/campaigns.ts
**admin/donations: Add payment related to donation section** 
- Includes payment data such as provider, billingName, billingEmail. Requested by the finance team for easier referencing.
Requires  [#609](https://github.com/podkrepi-bg/api/pull/609) to be merged, as it changes the API response to include the necessary payment data, referenced by the table
**admin/payments: Remove duplicate of status filter dropdown**
**admin/payments:  Reordered payments field**
Moved payment type, and payment provider as to first spots..
=> admin/donations: Add payment related fields to donation section

.github/workflows/release.yml, .github/workflows/tests.yml
It appears, the issue  we had in the past got fixed
=> Bring back k8s manifest scan job

src/components/admin/donations/grid/GridAppbar.tsx, src/components/admin/donations/grid/GridFilters.tsx, src/components/admin/payments/grid/GridFilters.tsx
There was an issue, caused by Filter value referencing donationStore.provider, rather than donationStore.paymentProvider as its declared in the mobx state. This caused react error, due to switching from uncontrolled to controlled component, which also caused inability to clear out this specific filter.
=> admin/payments: Fix provider filter 

src/components/client/campaigns/CampaignFilter.tsx, src/components/client/campaigns/CampaignsList.tsx, src/components/client/campaigns/CampaignsPage.tsx, src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.styled.tsx, src/pages/campaigns/index.tsx
pages/campaigns/index.tsx: Run asynchronous tasks concurrently
campaigns/CampaignFilter.tsx: 
- Remove unnecessary array.filter call, when no filter is set
- Replaced `<ImageList>` with Grid
/campaigns/CampaignsList.tsx: 
- Replaced index with campaign.id as a component key for the card
/campaigns/CampaignsPage.tsx
- Set header tags according to aria best practices
=> pages/campaigns: Optimizations and improvements

.github/workflows/release.yml, .github/workflows/tests.yml
It appears after uncommenting the scan_manifest job the indentation was not done correctly, resulting in the whole job failing.
Tests:
Checked the affected yaml files, in a couple yaml validators, seems ok now.
=> fix: Indent scan_manifest job correctly in yaml files

src/components/client/faq/FaqPage.tsx
Temporarily hide Attract donators and Corporate partnership tabs from FAQ page since they currently contain inaccurate information.
=> Temporarily hide Attract donators and Corporate partnership tabs from FAQ page

src/components/client/campaigns/CampaignInfo/CampaignInfoStatus.tsx
The chips on Campaign details page were not responsive which caused a horizontal scroll on mobile devices. Adding 
flexWrap: 'wrap' fixes this issue:
Before|After
---|---
=> Remove horizontal scroll on Campaign details page on mobile

src/components/client/campaigns/DonorsAndDonations.tsx
The order of public donation has changed, back to the value of createdAt field in descending order.[#api620](https://github.com/podkrepi-bg/api/commit/3089a38184bb87701d2c450020d24fd8192c08bd). This change is necessary to prevent any confusion, due to mismatch between the order of a donation, and the shown date of a donation to the end user.
=> DonorsAndDonations.tsx: Use createdAt field, to show when donation was created

src/common/hooks/donation.ts, src/components/admin/payments/modals/RefundModal.tsx
- Added auth header to /donation/payments:/:id endpoint, according to changes in backend.
- Fixed an issue which caused the initial value of extPaymentIntentId, to not be updated when payment's data has been retrieved.
=> admin/payments: Fix refund button not working

src/components/admin/campaigns/grid/OrganizerSelect.tsx, src/components/admin/donations/grid/Grid.tsx, src/components/admin/organizers/grid/Grid.tsx, src/components/client/campaigns/CampaignInfo/CampaignInfoOrganizer.tsx, src/components/common/person/PersonInfo.tsx, src/components/common/person/PersonSelect.tsx, src/gql/campaigns.ts, src/gql/person.d.ts
It was reported, that when corporate profile is campaign's organizer, the name of the representative is shown instead of the company name.
=> fix: Show company name if campaign organizer is corporation

src/components/admin/donations/grid/RenderEditPersonCell.tsx, src/gql/donations.d.ts
Resolves issue which causes, inability to edit either payment or donation data, such as person or billingEmail
=> fix: Resolve not being able to edit payment or donation data

src/components/client/campaign-news/CampaignNewsList.tsx, src/components/client/campaigns/CampaignNewsSection.tsx, src/components/common/QuillStyleWrapper.tsx
This way the See more, See less buttons wont be visible if text is just around the height limit
Closes #1781
=> fix(campaign-news): Adjust initial article height with font's lineHeight

README.md, public/locales/bg/campaigns.json, public/locales/en/campaigns.json, src/components/client/campaigns/CampaignDetails.tsx
Translation for Financial Reports
There no translation for financial reports
before : 
after :
=> Adding translation for Compaign Details Financial Reports

.eslintrc.js, src/common/hooks/affiliates.ts, src/components/client/auth/profile/AffiliateProgramTab.tsx, src/components/client/notifications/CampaignSubscribeModal.tsx, src/components/client/notifications/GeneralSubscribeModal.tsx, src/components/client/notifications/SubscriptionPage.tsx, src/components/common/CookieConsentPopup.tsx
next-i18next offers SSR support. Although we don't need it specifically for every component it is better to prefer over react-i18next, in order to maintain consistency.
- Added eslint rule to prevent react-i18next imports
=> refactor: Replace react-i18next imports with next-i18next 

src/common/routes.ts, src/components/client/campaign-application/CampaignApplicationPage.tsx, src/pages/campaigns/application.tsx
Create a new protected route for campaign applications connected to [Epic #1842](https://github.com/podkrepi-bg/frontend/issues/1842)
2. Visit `http://localhost:3040/campaigns/application`
=> feat: create a protected route for campaign applications (Epic #1842)

src/components/common/navigation/AdminLayout.tsx
Fix Admin panel being accessible by normal users. Renders NotFoundPage whenever non-admin user attempts to visit /admin/*  URL.
Closes [api#642](https://github.com/podkrepi-bg/api/issues/642)
2. Attempt to visit any admin 
3. Should see 404 page not found.
https://podkrepi.bg/admin/*
=> fix: Admin ui accessible by normal user

public/locales/en/campaign-application.json
Add translations in English for the campaign application organizer step as requested in this task https://github.com/users/gparlakov/projects/1/views/1?pane=issue&itemId=67658316
*Connected to [Epic #1842](https://github.com/podkrepi-bg/frontend/issues/1842)
2. Visit `http://localhost:3040/campaigns/application`
=> fix: add translations in English for the campaign application organizer step (Epic #1842)

src/components/client/irregularity/Actions.tsx, src/components/client/irregularity/helpers/Irregularity.styled.tsx
- Made 'Back' button contained instead of primary.
- Adjusted position of the buttons on mobile.
- Removed the empty space above the buttons.
=> Update the buttons on Irregularity page

src/components/client/campaign-application/CampaignApplicationForm.tsx, src/components/client/campaign-application/CampaignApplicationPage.tsx
Prefill campaign application organizer form values from current user as requested in the following task https://github.com/users/gparlakov/projects/1/views/1?pane=issue&itemId=68583764
*Connected to [Epic #1842](https://github.com/podkrepi-bg/frontend/issues/1842)
2. Visit `http://localhost:3040/campaigns/application`
=> feat: prefill campaign application organizer form values from current user (Epic #1842)

src/components/client/blog/BlogPage.tsx, src/components/client/blog/BlogPostPage.tsx
Only published blogs are shown in our site, thus it is more appropriate to show the published_at date.
=> chore(blog): Show published_at date instead of created_at

src/components/client/campaign-news/CampaignNewsPage.tsx
Their position will be set by the quill editor instead.
=> fix(campaign-news): Remove center style for video and img

src/components/client/faq/FaqPage.tsx, src/components/client/layout/Layout.tsx, src/components/client/layout/ScrollToTop.tsx
- Added Scroll to top button on each page of the website. It is shown when the user scrolls down more than 700px.
- Replaced the deprecated pageYOffset with scrollY.
The changes are discussed with the design team.
=> Add Scroll to top button

src/components/admin/documents/Form.tsx
Updated the error message below type field on 'Create new document' form on Admin panel:
We do not need English translation for the text since it is present only on the Admin panel.
=> Update error message when creating new document (Admin)

src/components/admin/irregularity/admin/grid/CreateForm.tsx
- Adapted the height of the fields on Irregularity form:
- Arranged file's imports.
=> Adapt fields' height on Irregularity form [Admin panel]

src/components/admin/campaigns/grid/CreateForm.tsx, src/components/admin/campaigns/grid/EditForm.tsx, src/components/admin/expenses/Form.tsx, src/components/admin/recurring-donation/Form.tsx, src/components/admin/transfers/CreateForm.tsx, src/components/admin/withdrawals/CreateForm.tsx, src/components/admin/withdrawals/EditForm.tsx
The changes will close https://github.com/podkrepi-bg/frontend/issues/1786 and update positive amount error message on all forms in the Admin panel.
=> Update positive amount error message on Admin panel forms

.devcontainer/devcontainer.json
- to enable vscode users to just open the dev container and have them be ready to go in minutes
- the config follows https://github.com/podkrepi-bg/dev-containers/blob/main/nodejs/README.md
- and pushes to the next version 1.2.0 which fixes the vscode unsupported alpine image error
=> chore: add devcontainer.json

src/components/client/campaigns/CampaignsList.tsx
- Added pagination on Campaigns page.
- Showed 20 campaign initally on the page.
Relates to https://github.com/podkrepi-bg/frontend/issues/1880.
=> Add pagination on Campaigns page

src/components/admin/recurring-donation/Form.tsx
Fixed id after choosing a campain in recurring donations in Admin panel:
Before|After
---|---
The id is set in handleCampaignSelected function when the user chooses a campaign. The issue was caused by setting an initail value on sourceVault when the id is already present, so I reset it to '' in the object.
=> Fix id after choosing a campaign (Admin panel)

src/components/common/ConfirmationDialog.tsx
Closes #[issue-1830](https://github.com/podkrepi-bg/frontend/issues/1830)
Desktop layout:
Mobile layout:
Before|After
---|---
=> close button added to Confirmation Dialog

src/components/common/form/FormRichTextField.tsx
Closes #[issue-1847](https://github.com/podkrepi-bg/frontend/issues/1847)
Before|After
---|---
=> show only one error msg for description field

.env.local.example, README.md, e2e/tests/regression/campaign-application/campaign-application-create.spec.ts, e2e/utils/fixtures.ts
- add a login fixture
- add a test that verifies the current admin list of campaign applications
Authentication of a user in e2e tests context 
Verification of Admin Campaign Application pages 
run the e2e tests
=> chore: add admin campaign applications

README.md, e2e/README.md, e2e/tests/regression/campaign-application/campaign-application-giver.spec.ts, e2e/utils/fixtures.ts, src/components/admin/campaign-applications/CampaignApplicationsGrid.tsx
Commits 
- [chore: e2e test for organizer edit and delete a file](https://github.com/podkrepi-bg/frontend/commit/12a7a2aff2c77b88d4e339184bcefe3307a9b02f)
- [chore: add auth e2e test readme section](https://github.com/podkrepi-bg/frontend/commit/0112db6aa6951fe630708d428eee5c1f46535506)
=> Admin campaign applications e2e tests part 3 file download or delete

src/components/client/layout/LocaleButton.tsx
Closes #1909 
Styling of the Locale button in the navigation not adjusted for mobile version - it is the same as the desktop version, while the other tabs` styles differentiate.
Styles of all MobileNav list items must be unified.
To solve that, i added sx property on the Locale button to style it for breakpoints below 900px
Before|After
---|---
1. Resize the window to width below 900px, which is the breakpoint where the navigation switches mobile/desktop.
2. Hover over the Locale button - it should have the blue color that appears on hovering register/login buttons and transparent background.
3. The new style shouldn't affect the button with breakpoints above 900px.
=> Adjust locale button style on hover

src/components/client/donation-flow/steps/payment-method/PaymentDetailsStripeForm.tsx
Closes #1761
Enhance the component's usability for individuals with varying levels of technical expertise by adding an onInput handler that removes non-letters, non-spaces, and non-hyphens, and replaces consecutive hyphens/spaces with a single character.
Before|After
---|---
1. Go to a donation page 
2. Choose card payment
3. Try adding numeric/other symbols in the name input field. Only Letters, spacing and hyphens should be allowed
Tested with different name combinations in regex 101 tool.
=> Card holder name restriction

src/components/client/campaign-application/steps/CampaignApplicationBasic.tsx, src/components/client/campaign-application/steps/CampaignApplicationDetails.tsx, src/components/client/campaigns/CampaignTypeSelect.tsx
- fix order of fields (make the goal the last field on the 3-rd step)
- remove "Membership" from the list of campaign types (it's a system type)
=> fix: campaign application

README.md, e2e/tests/regression/campaign-application/campaign-application-giver.spec.ts
Since we filter out the `Membership` type the e2e test fails b/c the one we want to select is indeed the membership one.
=> fix: campaign application e2e test

public/locales/en/index.json
Fixed the typo in heading of "How does Podkrepi.bg work?" section.
Closes #1986
Before|After
---|---
=> Fix typo in homepage section heading

src/components/client/campaigns/CampaignDetails.tsx, src/components/client/notifications/CampaignSubscribeModal.tsx, src/components/client/notifications/GeneralSubscribeModal.tsx
Made necessary styling changes to make "Subscribe to campaign news" dialog and "general subscribe" dialog responsive.
Closes #{[1984](https://github.com/podkrepi-bg/frontend/issues/1984)}
Before|After
---|---
General Subscription:
Campaign Subscription:
Go to https://podkrepi.bg/
Select a campaign.
Choose "Абонирайте се за email известия за кампанията.". Log in as a guest or with your credentials.
Go to mobile view.
Observe the dialog.
=> fix: make subscribe dialog responsive 

src/components/client/index/sections/CompletedCampaignsSection/CompletedCampaignsSection.styled.tsx, src/components/client/index/sections/PlatformStatisticsSection/PlatformStatisticsSection.styled.tsx
[screen-capture (2).webm](https://github.com/user-attachments/assets/055c4d01-4210-40b4-b486-16cdd5f76da5)
Slick dots are with relative position instead of absolute. This way we wont see overlaps between different elements.
https://github.com/podkrepi-bg/frontend/issues/2025
=> fixed dots overlap on section

src/components/common/navigation/NestedMenu.tsx, src/components/common/person/grid/Grid.styled.tsx, src/components/common/person/grid/Grid.tsx
adjust style in NestedMenu using sx and extract Grid.tsx styled components.
Related to #2001
=> replace inline style styled components

public/locales/bg/common.json, public/locales/en/common.json, src/components/client/layout/Footer/SocialIcons.tsx
Closes #2036 
- Added new icon in the footer.
- Had to add Discord icon as inline SVG as MUI lacks this Icon
- Icon link point to new page -> https://discord.com/invite/nZAeCb9YzP
- Added translation for the aria-label
Before|After
---|---
- Footer
Desktop and mobile - OK.
Scroll to the footer.
All that have the footer component visible
None.
None
=> Adding discord link and icon in the footer - resolves #2036
